### ISSUE TITLE
Consulta X : Cómo funcionan las asistencias en el juego???

### ISSUE THREAD

**Issue by isidorabecker** [IIC2413/Syllabus-2021-2#101]
Holaaa !!, no entiendo quien asiste a quien :(

**Comment by ironcadiz** [comment]
Hola!
Cuando dos o  más jugadores contribuyen a dejar ko a un jugador del otro equipo, aquel que dio el último ataque queda registrado en una fila de la tabla `ko` y los demás quedan como que "asistieron" por lo que cada uno tiene una fila en la tabla `asistencia`.

En términos de los datos, el jugador de id `asistencia.id_jugador` asistió al jugador de id `ko.id_jugador` a noquear al jugador de id `ko.id_victima` cuando  `asistencia.id_ko = ko.id`
