### ISSUE TITLE
Consulta Código Entregado:  [Error Al ejectutar Celdas Entregadas por el Curso :]

### ISSUE THREAD

**Issue by cfernandek** [IIC2413/Syllabus-2021-2#102]
Hola, empezando el control  2, al ejecutar las dos primeras celdas para descargar la base de datos y montarla en postgres, me sale un error, con el que no puedo seguir desarrollando el control ya que no se reconocen las relaciones. Al correr la primera celda el error es el de la primera foto (me sale permission denied a la base de datos) y la segunda celda el error es el de la segunda foto. ¿Cómo puedo arreglar esto? No he modificado nada del código entregado.

De antemano muchas gracias.

<img width="1286" alt="Captura de Pantalla 2021-10-07 a la(s) 16 14 28" src="https://user-images.githubusercontent.com/69773929/136448201-a4a8ef79-fc96-485f-bf35-8ff86573a649.png">
<img width="853" alt="Captura de Pantalla 2021-10-07 a la(s) 16 15 01" src="https://user-images.githubusercontent.com/69773929/136448303-56023e3e-015c-468b-beae-5ddb5c6d88e0.png">

**Comment by rjherrera** [comment]
hola! eso es probable que pase al correr dos veces la celda con los steps iniciales para dejar configurado postgres. Si se fijan lo que pasa es que en su colab ya tienen configurada la base de datos y los roles, y al intentar crear las cosas de nuevo, falla porque ya existen.

Para solucionarlo, en colab pueden ir a `Entorno de ejecución` y después hacer click en `Restablecer estado de fábrica del entorno de ejecución`. Idealmente los comandos de esas celdas los deberían correr solo una vez y no tener problema para ejecutar los de más adelante, pero si les vuelve a pasar, con esos pasos debería solucionarse. 

Recuerden que en colab no es necesario ejecutar todos los steps cada vez, pueden ejecutar los primeros de configuración una sola vez, y los de probar sus consultas más adelante las veces que quieran sin re-ejecutar los primeros.

**Comment by cfernandek** [comment]
Muchas gracias, ahí funcionó @rjherrera !!
