### ISSUE TITLE
Consulta score y timestamp

### ISSUE THREAD

**Issue by tomytable** [IIC2413/Syllabus-2021-2#103]
Hola,
Cuando para un mismo jugador en una misma partida tengo distintos puntajes con timestamps también diferentes, entonces considero que el puntaje total de este jugador será el que tenga un mayor timestamp? O la suma de cada valor de puntaje?

Noté que los puntajes en la mayoría de las veces crecen cuando pasa el tiempo por lo que tendería a asumir que debo considerar solo el dato con un mayor timestamp??

Gracias

**Comment by rjherrera** [comment]
es la suma, en el fondo como se dice [acá](https://github.com/IIC2413/Syllabus-2021-2/issues/88#issuecomment-937861731) cada instancia de score es "una ganada de puntaje", por lo tanto puede ganar puntaje varias veces y se suma.
