### ISSUE TITLE
No puedo ejecutar control 2

### ISSUE THREAD

**Issue by santandergc** [IIC2413/Syllabus-2021-2#104]
Hola! no puedo ejecutar el primer cuadro del cuaderno del control 2, me tira este error, como si no tuviera permiso para acceder al drive. Estoy desde mi cuenta uc.
![1](https://user-images.githubusercontent.com/80907322/136450262-e78c5449-f463-497b-88f2-2e4faab551f2.PNG)
![2](https://user-images.githubusercontent.com/80907322/136450286-3c05ae79-af2d-488e-a2fd-49258aa350e9.PNG)
Me aparece eso, que puedo hacer?

**Comment by piacabrera** [comment]
x5
