### ISSUE TITLE
Consulta Item 2

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2413/Syllabus-2021-2#107]
Hola! Para el item 2 nos piden que ejecutemos sentencias SQL. En este sentido no me queda claro si nos piden crear las tablas y poblarlas para ver que funcionen o solo debemos crear las tablas y justificar por qué son buenas tablas?

Desde ya muchas gracias.

**Comment by rjherrera** [comment]
con crear las tablas y restricciones, además de justificar, basta. De todas formas puedes poblar si lo estimas conveniente, pero lo pedido es crear y justificar.

**Comment by fernandolalanne** [comment]
Muchas gracias profesor. 
Saludos y buenas noches
