### ISSUE TITLE
Error control 2: UsageError: Cell magic `%%sql` not found.

### ISSUE THREAD

**Issue by BenjaRubio** [IIC2413/Syllabus-2021-2#109]
Hola, ejecuto el control y hasta la celda que dice "Si la siguiente consulta funciona bien entonces estas listo para empezar" esta todo bien, pero después cuando empiezo a escribir mis propias consultas derrepente me tira ese error

**Comment by rjherrera** [comment]
cuando pasa eso es porque no carga la extensión de SQL para colab, si corres las primeras celdas de setup debería funcionar bien, porque una de ellas incluye `%load_ext sql`, pero para evitar correr esos steps cada vez que te pase puedes agregar ese código en otra celda si te pasa de nuevo.
