### ISSUE TITLE
Consultas sobre pregunta SQL

### ISSUE THREAD

**Issue by Nicolemarin** [IIC2413/Syllabus-2021-2#11]
1. para hacer la parte 2.2, o sea _"Encuentre los nombres de los convencionales que hayan asistido a alguna sesión entre los días 01/09/2021 y 03/09/2021"_ con SQL,
solo se debe hacer **1 consulta? o sea solo un "bloque"** de: 
**SELECT
FROM
WHERE**?

2. y para esa pregunta, **las condiciones de joins y de las selecciones** (si lo analogamos a álgebra relacional), **todas esas condiciones van juntas dentro del where**?

Gracias de antemano

**Comment by JuanpaBC** [comment]
x2 la duda

**Comment by amparostevens** [comment]
Hola! 🌟

La consulta se puede hacer dentro de un solo bloque, pero si te acomoda lo puedes dividir en más consultas. 

En caso de hacer una sola, en el WHERE deberían ir todas las condiciones. En caso de hacer más de 1, vas a tener varios WHERE con las condiciones que estimes necesarias.
