### ISSUE TITLE
Consulta parte II : Ataques y bolsimones

### ISSUE THREAD

**Issue by benjamincaro** [IIC2413/Syllabus-2021-2#114]
No entiendo bien el enunciado. ¿Podría interpretarlo como que existe el ataque impactrueno en nivel básico, el impactrueno nivel intermedio e impactrueno nivel avanzado? Por ejemplo, si pikechu tiene los ataques impactrueno y látigo, significa que tiene pares (impactrueno, látigo) básicos, (impactrueno, látigo) intermedios y (impactrueno, látigo) avanzado?. O quiere decir que cada bolsimon tiene dos ataques (a,b) de nivel básico, (c,d) de nivel intermedio y (e,f) de nivel avanzado, donde cada ataque pertenece a un nivel fijo? Por ejemplo, el ataque **a** siempre sería básico.

**Comment by raibd** [comment]
Hola, para esta misma pregunta, para hacer las tablas hay que hacerlo desde un archivo csv o algo asi?

**Comment by rjherrera** [comment]
sí y no jaja, con implementar el esquema con sentencias sql nos referimos a usar los CREATE TABLE con las restricciones que consideres necesarias, para que se refleje el esquema final después de los nuevos elementos agregados en la pregunta 2
