### ISSUE TITLE
Consulta Parte 1 Pregunta 4 : Consideracion a la hora de calcular el tiempo total fuera de combate

### ISSUE THREAD

**Issue by Diegothx** [IIC2413/Syllabus-2021-2#115]
Haciendo esta pregunta me di cuenta de un detalle a tomar en cuenta. Cuando un jugador muere cerca del final de la partida, este puede terminar no cumpliendo su tiempo de espera para reapacer en caso de que la partida termine antes de que se cumpla este tiempo asignado. ¿Esto hay que considerarlo o se asume como si la suma de los tiempo fuera de combate de los ko fuera el tiempo total nomas?
Dando un ejemplo, me refiero a que si quedan 5 segundos de partida, y un jugador muere, quedando con un cooldown de 40 segundos, ¿tenemos que considerar como si cumplio los 40 segundos? o consideramos que solo cumple los 5 segundos que quedan?

**Comment by rjherrera** [comment]
buen punto! la idea es hacer la consulta solo considerando la información de segundos_reaparecer, sin importar ese caso borde.
