### ISSUE TITLE
Consulta PARTE 1 EJERCICIO 3 :  problema con el resultado

### ISSUE THREAD

**Issue by elpelaoloco** [IIC2413/Syllabus-2021-2#118]
Hola, me esta pasando que en la pregunta 3 si muestro el username y las veces que han ocupado al pokemon me sale cierto orden y frecuencias de uso, pero si al mismo código le agrego que muestre también los ratings me sale un resultado completamente diferente en términos de usernames y la frecuencias de uso del pokemon.  revise mi código varias veces y en ninguna parte el rating influye en que la tabla cambie de esa forma.  No se que hacer ni cual de las dos formas es la correcta ayuda plzzzzzz

**Comment by ironcadiz** [comment]
Eso es una duda muy específica de como estás resolviendo el control y no te la podemos resolver por acá.
