### ISSUE TITLE
Consulta parte 1 pregunta 4: formato del resultado

### ISSUE THREAD

**Issue by jamigone** [IIC2413/Syllabus-2021-2#119]
Hola! No me queda claro cuál debe ser la tabla esperada en esta consulta. Dado que se pide el tiempo total fuera de combate de cada bolsimon, ¿la tabla serían 2 atributos (tiempo_total_fuera, bolsimon)?
De ser así, ¿debemos colocar como 2do atributo el id del bolsimon o su nombre?

Saludos :)

**Comment by ironcadiz** [comment]
Si, es eso.
Debe ser el nombre
