### ISSUE TITLE
Consulta sobre cómo aplicar el operador rho en SQL

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#12]
Hola, quería saber si existe algún comando en SQL que imite la función de rho en álgebra relacional. Me parece que no alcanzamos a verlo en la clase pasada.

Desde ya gracias.

**Comment by amparostevens** [comment]
Hola! 

El operador _rho_ equivale al uso de **WHERE** en SQL. 

Por ejemplo, la siguiente consulta en álgebra relacional
![image](https://user-images.githubusercontent.com/53883653/132038509-a90f1cd9-4d44-4bcb-87d4-f567eef39d38.png)

es equivalente a `SELECT * FROM peliculas WHERE director='C.Nolan'`

**Comment by amparostevens** [comment]
Hola!

En SQL puedes utilizar el comando **AS** para renombrar una columna o tabla con un alias. Puedes encontrar una explicación y ejemplos [aquí](https://www.w3schools.com/sql/sql_ref_as.asp) y en [esta](https://www.postgresqltutorial.com/postgresql-alias/) página.

**Comment by JuanpaBC** [comment]
gracias, vi las páginas y entiendo mejor, pero me queda aún una duda: cómo puedo darle un nombre a una tabla que no existe aún? Por ejemplo, cómo haría para decirle a SQL que quiero llamar "tabla AB" al join de la tabla A con la tabla B (existentes)?

Desde ya gracias.
