### ISSUE TITLE
Entrega 2 Impar: sobre multiplicidad subg - gen

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#123]
Hola, esperando que estén bien, 

tenía la duda de si un subgénero -tanto en el caso de las series como de las películas- solo puede pertenecer a un género o puede pertenecer a más de uno. Adicionalmente, me preguntaba si existe algún subgénero que pueda no pertenecer a ningún género.

Desde ya gracias.

**Comment by arpincheira** [comment]
Hola, un subgénero podría existir a más de un género, mientras que lo segundo que mencionas no puede pasar. Lo otro, en esta entrega existe la libertad de modelar la relación de los géneros y subgéneros de películas y series es un macrogrupo de géneros(contrario a lo indicado en la entrega 1). Sin embargo se debe seguir respetando la "jerarquía" en lo que respecta a la relación género y subgénero de.

**Comment by CarolinaYanez** [comment]
Hola, no entiendo a qué te refieres con hacer un macrogrupo de géneros, respetando la jerarquía de la relación de género y subgénero. ¿Te refieres a dejar de hacer la distinción entre ambos? ¿Pero cómo se logra mantener la jerarquía en ese caso? ¿Qué sentido tienen los subgéneros si en los datos no se indica a qué subgénero pertenecen las películas ni series?

**Comment by arpincheira** [comment]
Hola, la explicación es la siguiente:

En esta entrega existen distintos géneros, los cuales a su vez pueden ser o no ser subgéneros de otros géneros. El tema es que el que sean subgéneros de otro género no debe influir en las películas y series, dado que estas solo poseen uno o más géneros(**pista** a ellas no les influye que un género sea o no subgénero de otro pues solo les interesa relacionarse con los géneros). Ahora, la entrega pasada decía que las películas y series tenían uno o más géneros y subgéneros, pero en esta entrega existe la libertad de modelarlo como película tiene géneros y los géneros pueden o no ser subgénero de otro género, siendo esto último a lo que me refería con "jerarquía de géneros".

**Comment by JuanpaBC** [comment]
hola, tratando de aplicar lo que me explicaste en tu respuesta, me cuesta un poco dibujar la relación de que un género sea subgénero de otro en el diagrama ER, pues no encontré en las slides de esta materia un ejemplo de relación sobre una misma entidad. Lo sgte representación de una relación que relaciona géneros con géneros para establecer quién es subgénero de quién es correcta?
![image](https://user-images.githubusercontent.com/80859173/136843788-ee42ad58-7869-4e42-99d3-0469f685f438.png)

Espero no estar causando problemas con la foto, si es que sí, pido disculpas de antemano.

**Comment by arpincheira** [comment]
Hola, en primer lugar cuidado con la foto(edité tu comentario para evitarla), pero la relación de géneros subgéneros que planteas si se puede dar y sería correcto modelarla de esa manera.

**Comment by JuanpaBC** [comment]
gracias!
