### ISSUE TITLE
Entrega 2 Impar: multiplicidad subg/gen - peliculas/series

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#124]
Hola, esperando que se encuentren bien,

tenía dos dudas que son idénticas en su forma:

* Una película/serie siempre tiene género? puede existir un género al cual ninguna película/serie pertenezca?
* Una película/serie siempre tiene un subgénero? puede existir un subgénero al cual ninguna película/serie pertenezca?

Desde ya muchas gracias.

**Comment by arpincheira** [comment]
Hola, efectivamente tanto películas como géneros siempre tienen un género y tengo entendido que lo segundo que mencionas no puede pasar. 

Ahora, en lo que respecta a los subgéneros, dado que los datos de la entrega indican múltiples géneros de películas y no subgéneros de estas, te recomiendo tomar el supuesto mencionado en la issue #123, dando importancia a la jerarquía de géneros pero no realizando la subdivisión género y subgénero de película.(pues si bien se podría decir que son cosas parecidas, en la realidad son cosas distintas pues implica que una película puede tener uno o más géneros, entre los cuales alguno puede ser un subgénero de uno de los géneros existentes en los datos)
