### ISSUE TITLE
Entrega 2 Impar: multiplicidad Usuarios - Proveedores

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#125]
Hola, esperando que estén bien, tengo la sgtes dos dudas respecto a la multiplicidad en la relación entre las entidades Usuarios y Proveedores:

* Los usuarios si o si tienen que estar suscritos a al menos una suscripción? no pueden haber usuarios que no estén suscritos a ningún plan (proveedor)? 
* Los proveedores tienen que sí o sí tener aunque sea un usuario como cliente suscrito?

Desde ya muchas gracias.

**Comment by arpincheira** [comment]
Hola, responderé a tus dudas una en una:

* Puede ocurrir que hayan usuarios que se hayan suscrito y ya no lo estén.
* No es 100% necesario que tengan por lo menos un cliente suscrito(Puede que sean malos proveedores o no atraigan a la gente). Pero creo que en los datos entregados esto no ocurre y por lo menos todos tienen mínimo un usuario que está o alguna vez estuvo inscrito.
*

**Comment by JuanpaBC** [comment]
muchas gracias! me queda claro
