### ISSUE TITLE
Entrega 2 Impar: multiplicidad peliculas/series - proveedores

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#126]
Hola, esperando que se encuentren bien, tenía las sgtes dos dudas sobre la relación tanto de Películas como de Series con la entidad Proveedores:

* Los proveedores deben ofrecer como mínimo una película, una serie, o una de ambas?
* Pueden existir películas/series que no son ofrecidas por ningún proveedor?

Desde ya muchas gracias.

**Comment by arpincheira** [comment]
Hola, con respecto a tu primera pregunta, pueden existir proveedores que no ofrezcan películas y proveedores que no ofrezcan series, pero no puede ocurrir que exista un proveedor que no ofrezca ninguna de ambas. De todas formas es correcto añadir en los supuestos de la modelación, que todo proveedor va a ofrecer **a lo menos** una serie y una películas.

* Efectivamente pueden existir películas y series que no son ofrecidas por ningún proveedor, pero en lo que respecta al universo de datos que estamos tratando(lo que se debe modelar en esta entrega), eso no puede ocurrir, por lo que las películas existentes las provee a lo menos un proveedor, ya sea por medio de pagos o gratuita.

**Comment by JuanpaBC** [comment]
perfecto, muchas gracias!
