### ISSUE TITLE
victoria bolsimon: parte I pregunta 8

### ISSUE THREAD

**Issue by graci007** [IIC2413/Syllabus-2021-2#128]
Hola!, estoy un poco confundida respecto a lo que se considera una victoria para el bolsimon en la pregunta 1.8, ¿se consideraria victoria los ko hechos por el bolsimon? en ese caso ¿solo deberiamos ver la cantidad de kos de cada bolsimon para sacar el porcentaje de victorias ?

**Comment by ironcadiz** [comment]
Esto lo respondí en #100
