### ISSUE TITLE
Consulta X : google collab

### ISSUE THREAD

**Issue by jvergara-sanguesa** [IIC2413/Syllabus-2021-2#131]
Hola, estoy usando google collab y a cada rato me deja de funcionar y despues vuelve o me deja de reconocer sql. Existe alguna otra plataforma donde pueda hacer el control??? ya que todo el rato me tira problemas.

**Comment by afalarconm** [comment]
x2

**Comment by mathimadsen17** [comment]
x4

**Comment by MotxiGer** [comment]
medio nombre compa
