### ISSUE TITLE
Consulta 1 : [corta] Mostrar más datos de los pedidos

### ISSUE THREAD

**Issue by fernandosmither** [IIC2413/Syllabus-2021-2#135]
¿Podemos mostrar más datos de los pedidos en las consultas SQL?

Ejemplo, en 1.4 nos piden "Tiempo en segundos que cada bolsimón pasó fuera de combate"

Puedo mostrar en el resultado cosas como el nombre del bolsimon, su id, y otras cosas? (con criterio, no me refiero a usar *)

**Comment by ironcadiz** [comment]
Entregar filas demás está incorrecto

Entregar columnas demás va a quedar a criterio del ayudante si es que amerita descuento o no. Mejor no se complica nadie la vida si es que solo responden con lo que se pide jeje.
