### ISSUE TITLE
Consulta X : Solicitud de tiempo extra por problemas en el Colab

### ISSUE THREAD

**Issue by jadelanoa** [IIC2413/Syllabus-2021-2#138]
Hola, agradecería si fuera posible aplazar la entrega por todos los problemas que hemos tenido en el Colab.

**Comment by BenediktKd** [comment]
Me pasó lo mismo

**Comment by mathimadsen17** [comment]
Cada 10 minutos se pierden 5 por problemas de colab

**Comment by antoniacaceres** [comment]
Sii porfis, se cae mucho y además la ayudantía quedó muy encima):

**Comment by jpvergaralb** [comment]
xfa bor!

**Comment by antoniaalcayaga** [comment]
Me paso lo mismo, en verdad el tiempo se hizo nada :(

**Comment by fsotomutoli** [comment]
x2 y la ayudantía del control fue recién hoy :(

**Comment by martin-iturralde** [comment]
El colab no funciona nada bien! A veces tengo que estar hasta 20-30 minutos para que funcioné bien nuevamente. He perdido mucho tiempo al respecto. Más tiempo sería lo adecuado a la situación!

**Comment by benjavicente** [comment]
Otro tip para mejorar el rendimiento es probar antes las consultas con `LIMIT 1` u otro número razonable, ya que PostgreSQL va a considerar que solo se necesite esa cantidad de resultados y va a optimizar la consulta hecha a los datos con esta información.
