### ISSUE TITLE
Consulta 1.2  : Forma de mostrar la respuesta 

### ISSUE THREAD

**Issue by APeraltaS16** [IIC2413/Syllabus-2021-2#141]
Hola!, en la pregunta 1.2 nos piden mostrar el equipo que gana, importa mostrar mas datos en la tabla como por ejemplo el puntaje de este equipo. Esto mismo para todas las consultas, ¿pueden bajar nota por agregar mas datos de los pedidos aunque en estas tablas este todo lo pedido correcto?
Saludos!

**Comment by ironcadiz** [comment]
La idea es mostrar sólo quien ganó.
Como se dijo en otra issue igual. Una fila , una columna con 'azul' o 'rojo'
