### ISSUE TITLE
Consulta 1.4 : bolsimones sin tiempo de fuera de combate

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2413/Syllabus-2021-2#142]
Hola, 

En la consulta 4 : Para la partida de id 256 mostrar el tiempo en segundos que cada bolsimon pasó fuera de combate. Es necesario que aparezcan los bolsimones que no estuvieron tiempo fuera con un cero o pueden aparecer solo los que tuvieron tiempo fuera?

Gracias!

**Comment by APeraltaS16** [comment]
Hola!, me respondieron esto en la issue #97 :)
