### ISSUE TITLE
Consulta Parte II : [Enunciado Parte II]

### ISSUE THREAD

**Issue by cfernandek** [IIC2413/Syllabus-2021-2#143]
Hola,
Me gustaría saber si es que se puede agregar un atributo a las entidades ya creadas que fueron entregadas? Como por ejemplo agregarle una columna id_perro a la entidad usuario (no aplica al tema, es para no utilizar la misma idea del enunciado).

Gracias

**Comment by ironcadiz** [comment]
Si se puede.
Saludos!
