### ISSUE TITLE
Entrega 2 Par: Significado de columna cantidad en usuarios_actividades.csv

### ISSUE THREAD

**Issue by catalinacarter** [IIC2413/Syllabus-2021-2#148]
Hola! Respecto a los archivos csv, que significa la columna _cantidad_ en **usuarios_actividades.csv**?
Gracias!

**Comment by catalinacarter** [comment]
Super, gracias :)

**Comment by danvillablanca** [comment]
Una duda, ¿por qué se asume que la cantidad de horas es vacía cuando el juego tiene un veredicto positivo/negativo?
