### ISSUE TITLE
Problemas con cambio de contraseña en el servidor

### ISSUE THREAD

**Issue by Pabloski100** [IIC2413/Syllabus-2021-2#15]
Hola, estaba siguiendo los pasos de la wiki y cambie la contraseña del servidor de mi grupo, sin embargo, no me reconoce la nueva contraseña, supongo que apreté alguna tecla mal las dos veces que ingrese la clave que quería o algo similar, hay manera de solucionar eso?

**Comment by arpincheira** [comment]
Hola, si me indicas tu número de grupo puedo reiniciar su contraseña para que sea nuevamente la original

**Comment by Pabloski100** [comment]
Hola, es el grupo 4, muchas gracias de antemano, tendré mas cuidado

**Comment by arpincheira** [comment]
Listo
