### ISSUE TITLE
Entrega 2 Impar: Proveedores y Series

### ISSUE THREAD

**Issue by raibd** [IIC2413/Syllabus-2021-2#150]
Hola, estaba tratando de crear unas tablas a partir del archivo _proveedores.csv_, y resulta que distintos proveedores pueden ofrecer la misma serie y distintas series pueden ser ofrecidas por el mismo proveedor. En este caso no se cumplirían ninguna de las dos dependencias _proveedor -> serie_ y _serie -> proveedor_ (¿o estoy mal?). Por lo tanto como es que se normaliza una tabla que contiene al proveedor y las series que ofrece?

**Comment by arpincheira** [comment]
Hola, no te puedo dar la respuesta como tal pero te recomiendo fuertemente buscar sobre las relaciones N a N y su relación con BCNF y 3NF, hay varios artículos muy buenos sobre esta temática.
