### ISSUE TITLE
Entrega 2 Impar : [dos posibles primary key]

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2413/Syllabus-2021-2#152]
Hola!

Haciendo la entrega nos surgió una duda de materia, pero no hay issues de materia así que lo preguntaré por acá. ¿Qué sucede con la dependencia funcional si tengo dos posibles primary key, ya que ambas determinan por si solas a todos los otros atributos de la tabla?, Por ejemplo:

   X -> Y,W,Z
   Z -> Y,X,W

¿Esto es algo negativo?, ¿o en verdad da igual y solo habría que dejar una de las dependencia funcionales?

Graciaas! :)

**Comment by arpincheira** [comment]
Hola, te recomiendo ver la issue anterior #151
