### ISSUE TITLE
Entrega 2 Impar Apartado X : Incongruencias entre tablas (datos)

### ISSUE THREAD

**Issue by VicenteGM123** [IIC2413/Syllabus-2021-2#153]
Hola! revisando _pagos.csv_ nos dimos cuenta que la primera tupla dice que el usuario con _uid_ = 4 realizó un pago en la suscripción con _id_ = 392, pero luego, en _suscripciones.csv_ sale que la suscripcion con id = 392 es la del usuario con _uid_ = 106, y creo que esto ocurre en varios casos. Me gustaría saber si esto forma parte del proceso de limpieza que debemos hacer, o si es un error. En caso de que sea parte del proceso de limpieza: cómo tendríamos que hacer para no perder información en el intento? De antemano, muchas gracias.

**Comment by arpincheira** [comment]
Hola, eso si es un problema, hoy en la tarde/noche subiré los datos arreglados, de todas formas quiero anunciar que el problema está en la columna de subscripción_id, aparentemente ocurrió una confusión con unos cuantos datos. Muchas gracias por avisar.
