### ISSUE TITLE
Entrega 2 Impar: Tengo que usar los esquemas de las tablas?

### ISSUE THREAD

**Issue by Icarus328** [IIC2413/Syllabus-2021-2#154]
Hola, viendo los archivos .csv quería saber si tengo que modelar la base de datos usando los esquemas presentes en esos archivos o si puedo hacer mis propios esquemas usando esos datos para eliminar ciertas redundancias.

**Comment by arpincheira** [comment]
Hola, los datos que dimos no están normalizados pero toda la información que poseen es fundamental para la actividad. Por lo que si, debes basarte en ellos para poder hacer tu modelo pero debes realizar un proceso de normalización para poder ajustarlos a un nuevo modelo que esté en 3nf o en bcnf. 

Reitero, puedes hacer tus propios esquemas a partir de los datos(mira la issue #77) pero debes tener cuidado de no eliminar información importante.
