### ISSUE TITLE
Entrega 2 Par Apartado X: Esquemas

### ISSUE THREAD

**Issue by graci007** [IIC2413/Syllabus-2021-2#155]
Hola, tengo dudas respecto a los archivos entregados(CSV)
*no entiendo  si el diagrama debemos hacerlo respecto a las tablas creadas en la entrega 1 o realizarlo fielmente a las tablas entregadas por ustedes:
1. en el primer caso, no entiendo bien para que servirían los datos entregados.
2. en el segundo caso, faltan varias partes que a mi parecer son esenciales, entonces se podrían cambiar la forma de las tablas y modificarlas?
*debemos normalizar las cosas antes o después del diagrama ?

**Comment by arpincheira** [comment]
Hola, si me preguntas por cual de las dos me decantaría, yo me la juego por la puerta número 2(~not a Shrek reference~). 

Con respecto a lo segundo, me gustaría que me explicaras cuales son las partes que pueden ser esenciales y que faltan de los datos. Siguiendo por esta misma línea si, pueden realizar una normalización de los datos(recomiendo la issue #77 para que veas a lo que me refiero), pero **no puedes inventar datos**(no creo que alguien lo quiera hacer pero lo dejo claro por si es que sucede) y recomiendo encarecidamente respetar los ids entregados y no eliminar datos(son importantes todos).
