### ISSUE TITLE
Entrega 2 Impar Apartado 2.3 : Importar datos

### ISSUE THREAD

**Issue by aacampos3** [IIC2413/Syllabus-2021-2#156]
Hola,
tengo una duda al importar datos en el archivo ```multimedia.csv```, quería preguntar ¿qué significa la columna numero en las series?

**Comment by arpincheira** [comment]
Hola, aquí hay una pista:
<img width="1008" alt="Captura de Pantalla 2021-10-10 a la(s) 20 10 35" src="https://user-images.githubusercontent.com/37157550/136715869-300d4ad8-994c-4882-832e-b97f9b306ff4.png">
