### ISSUE TITLE
Entrega 2 Par Apartado 2.1: Índices en modelo E/R

### ISSUE THREAD

**Issue by mateogs** [IIC2413/Syllabus-2021-2#159]
Hola,
Como duda general, si en nuestra bdd queremos incluir ids para todas las tablas, ya sea para entidades o relaciones, debemos incluir los ids como atributos en el modelo E/R o no es necesario?

**Comment by benjavicente** [comment]
Hola! Incluyan todos los atributos en el modelo y el esquema, para dejar claro bien como se estructuran las tablas y como son sus restricciones (llaves primarias, llaves foráneas, tipos de datos, etc).
