### ISSUE TITLE
Duda entrega 1: que pide la consulta 6

### ISSUE THREAD

**Issue by Pabloski100** [IIC2413/Syllabus-2021-2#16]
Hola, estaba avanzando la entrega 1 y me confunde un poco la consulta 6, pide todos los gastos de los usuarios asociados a subscripciones o pide alguna especie de suma de los gastos de los usuarios?

**Comment by benjavicente** [comment]
Hola! Tanto para grupos impares como pares se pide que se muestre el gasto total (o suma de dinero) **para cada usuario** y no una "lista" de gastos, entonces si hay múltiples gastos se va a requerir algún tipo de agregación para juntar cada uno.
Ojo que **para esta entrega se pide que creen solo las primeras 3 consultas**, no tienen que preocuparse de como implementarlo, solo de sí se podría hacer con _alguna especie de suma_.
