### ISSUE TITLE
Entrega 2 Impar Apartado : Duda con disponibilidad proveedores

### ISSUE THREAD

**Issue by sr-kk** [IIC2413/Syllabus-2021-2#160]
Hola q tal

En el archivo de proveedores, el header de disponibilidad asumo que hace referencia a que si la serie o película esta disponible en la plataforma, pero me surge la duda de los valores que toma, ¿a qué hacen referencia?

**Comment by arpincheira** [comment]
Hola, estás seguro de que disponibilidad aplica para series y para películas? Como pista te puedo decir que cuando uno paga para poder visualizar un contenido de acceso temporal existe un cierto período de tiempo en que eso se encuentra disponible.

**Comment by sr-kk** [comment]
Gracias por el hint, ya me pude percatar
