### ISSUE TITLE
Entrega 2 Impar : [Monto/precio & Notación E/R]

### ISSUE THREAD

**Issue by Nicolemarin** [IIC2413/Syllabus-2021-2#161]
**Dudas sobre monto/precio**
1. En la tabla proveedores: ¿Qué diferencia hay entre **costo** y **precio**, y a qué se refiere con **disponibilidad**?
2. En la tabla “pagos v2”: ¿El **monto** se refiere a:
  -al pago de una suscripción, 
  -o al pago de una película, 
  -o al pago de ambas cosas?
3. En la tabla suscripciones: ¿el **monto**, a que se refiere?

Nosotras asumimos que el "monto" en la tabla pagos era "lo que se paga por suscripción" + "película arrendada", pero cuando nos ponemos en un caso particular de un pago, no nos dan los cálculos.

**Dudas sobre notación E/R:**
- Entre una clase y una subclase, pueden existir flechas (multiplicidades)?
- Una relación (un rombo), puede tener como atributo un **id de una entidad lejana** (no directamente relacionada con ella)?

Gracias

**Comment by arpincheira** [comment]
Hola, las respuestas son las siguientes:
1.  costo y precio son distintos(fíjate en su variación entre películas y proveedores).
2. monto es un pago genérico(esto puede ser una pista sobre la normalización O.o)
3. Te refieres a costo? Si es así, puede que tenga que sea sinónimo de mensualidad.

**Comment by Nicolemarin** [comment]
Gracias, pero no me quedó claro.

1. Sabemos efectivamente que costo y precio son distintos. Pero la pregunta es.. 
- el costo es el costo **de qué cosa**? de pelicula? de suscripcion? o otra de cosa?
- el precio es el precio **de qué cosa**? de pelicula? de suscripcion? o otra de cosa?
tratamos de encontrar la respuesta, comparando con otras tablas, pero no podimos llegar a nada.

2. ¿es el monto de pago de varias cosas? es como la suscripción? o es más que solo la suscripción (pelicula arrendada + suscripción, por ejemplo)?

Otra cosa... edité mi issue justo en el momento que contestaste, entonces agradecería mucho si pudieras responder el resto. muchas gracias :)
