### ISSUE TITLE
Entrega 2 Par Consultas

### ISSUE THREAD

**Issue by graci007** [IIC2413/Syllabus-2021-2#162]
Hola! tenia una duda con la parte de las consultas,
¿debemos hacer las  7 consultas explicitas como en la entrega 1?  o ¿en  la pagina web solo debemos dejar todo listo para que alguien haga las consultas?

**Comment by arpincheira** [comment]
Hola, son las 2, deben implementarlas en la página web y dejarlas explícitas en el informe. En el caso de que tengas dudas sobre lo que debe tener este te recomiendo revisar el apartado `reporte` del enunciado de la entrega 2.
