### ISSUE TITLE
Entrega 2 Impar: Titulo de peliculas

### ISSUE THREAD

**Issue by raibd** [IIC2413/Syllabus-2021-2#163]
Hola, es posible que hayan varias peliculas con el mismo titulo? por lo que veo no hay, pero pregunto mas que nada para las proximas entregas y por si afecta lo que hagamos ahora.  
Gracias

edit: ¿Y para nombres de capitulos de series?

**Comment by arpincheira** [comment]
Hola, en lo que respecta a los datos entregados, no. Ahora, recomiendo fuertemente que en su modelo consideren que si pueden existir películas con nombres repetidos(esto con el objetivo de hacer que sea más realista su modelo)
