### ISSUE TITLE
Entrega 2 Impar Consulta 6 : Obtener fecha actual en una consulta

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2413/Syllabus-2021-2#164]
Buenos díasss, para la consulta 6 se nos pide que la fecha de visualización de las series sea dentro del último año, hemos intentado varias maneras de obtener la fecha pero no hemos podido. Quizás nos estamos complicando de más y basta con poner que la fecha sea después de 01/01/2020 ja.

Resumen, la pregunta es como se puede obtener la fecha actual dentro de una consulta o, si esto no es necesario, confirmar que sirve con poner una fecha arbitraria nomásss.

**Comment by arpincheira** [comment]
Hola,  personalmente recomiendo decidir uno de los dos supuestos:
- Tomar año como "input" y por lo tanto realizar la consulta entre el primer y el último día del año.
- Hacer que php consiga la fecha actual y utilizarla al interior de la consulta. (mirar  [este link](https://www.php.net/manual/es/function.date.php) )

En cualquiera de los dos casos te recomiendo fuertemente ponerlo en el apartado de supuestos al interior de tu informe.
