### ISSUE TITLE
Entrega 2 Par Apartado 1: Duda sobre Diagrama E/R

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2413/Syllabus-2021-2#165]
Hola!

El diagrama E/R se debe realizar con lo que hicimos en la entrega 1? O debe ser con las tablas que enviaron para la E2?
Por dar un ejemplo, para la E1 con mi compañero creamos tablas en la que entendimos que Reseña podía ser una entidad y lo modelamos de esa manera, pero revisando las tablas que mandaron todo lo relacionado a reseñas se encuentra como atributos en la tabla: usuarios_actividad , entonces por eso tengo la duda.

Quedo atento,

Saludos

**Comment by benjavicente** [comment]
Hola! Los **datos entregados no están normalizados**, deben transformar las tablas entregadas para que sigan un modelo normalizado. Pueden utilizar lo que realizaron en la entrega pasada si se puede transformar los datos a su modelo anterior sin perdida de información y si su modelo está en BCNF o 3NF.
