### ISSUE TITLE
Entrega 2 Impar Apartado 1 : Duda géneros y subgéneros 

### ISSUE THREAD

**Issue by hjmacaya** [IIC2413/Syllabus-2021-2#167]
Hola! Me surgió una duda respecto a los géneros y subgéneros revisando los datos:

¿Cómo podemos identificar de que subgénero es una película o serie si existen géneros que engloban a más de un subgénero?

Ejemplo: (Celda 166) La película Jurrasic World posee genero de ciencia ficción y al acceder a la tabla de géneros-subgéneros encontramos que ciencia ficción tiene de subgénero a: ciencia de ficción apocalíptica (celda 3) y ciencia ficción cyberpunk (celda 22)
Entonces ¿Cómo podemos determinar a que subgénero pertenece Jurrasic World?

**Comment by minsoos** [comment]
En esa misma línea, ¿puede un subgénero aparecer como género de una película?
