### ISSUE TITLE
Problema ingreso al servidor codd.ing.puc.cl

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2413/Syllabus-2021-2#17]
> Ingresa los detalles de tu pregunta aquí, o da cualquier información adicional al título que ayude al equipo docente a responder tu pregunta
Hola! Ayer estaba tratando de ingresar al servidor del curso pero me arroja este problema

ssh: connect to host codd.ing.puc.cl port 22: Operation timed out

Si me pudieran explicar por qué podría estar pasando se los agradecería.

PD: el mensaje aparece después de ejecutar: ssh grupoXX@codd.ing.puc.cl

**Comment by rieg-ec** [comment]
A mi tambien me pasa, probablemente anda con problemas el servidor.

**Comment by arpincheira** [comment]
Hola, ahora debería estar funcionando el servidor

**Comment by mariizamb** [comment]
Hola! Tengo este mismo problema ahora, no sé si es por algún tema de "horario" en el cual el servidor funciona o si es por otra razón :(
Me sale el mensaje "Connection timed out"

**Comment by mariizamb** [comment]
Hola! Por alguna razón yo no puedo acceder a mi servidor pero mi compañero de equipo sí. Me sique saliendo el mismo error de siempre "no se puede conectar al puerto XX: connection timeout"
Hay alguna forma de poder solucionar esto?
Gracias por su tiempo

**Comment by arpincheira** [comment]
Hola, el error de conexión que te aparece se puede deber a múltiples causas, ya sea debido a un problema particular tuyo como a un problema del servidor. En este caso el servidor sigue funcionando correctamente y, dado que tu compañero se puede conectar también, creo que deberías buscar la causa de tu error particular.

Aquí te dejo un par de links en donde se habla de distintas causas y soluciones de dicho error: 

- https://www.siteground.com/kb/connection-timed-error-connecting-via-ssh/
- https://docs.digitalocean.com/products/droplets/resources/troubleshooting-ssh/connectivity/

Espero que alguna te sea útil.

**Comment by mariizamb** [comment]
Gracias! los reviso altiro

**Comment by mariizamb** [comment]
Hola @arpincheira lo que pasa es que revise lo que me mandaste pero al hacer un ping el servidor no me está pescando. Entonces no creo que sea un problema mío sino que del servidor o algo similar ya que parece que este no me está pescando.

Me sale lo siguiente:
PS C:\Users\mariela zambrano> ping codd.ing.puc.cl

Haciendo ping a codd.ing.puc.cl [146.155.13.72] con 32 bytes de datos:
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.

Estadísticas de ping para 146.155.13.72:
    Paquetes: enviados = 4, recibidos = 0, perdidos = 4
    (100% perdidos),
PS C:\Users\mariela zambrano>

Estoy haciendo algo mal o que me recomiendas hacer?
