### ISSUE TITLE
Entrega 2 Impar Apartado 2.3 : Asignar géneros a series (o capítulos)

### ISSUE THREAD

**Issue by minsoos** [IIC2413/Syllabus-2021-2#172]
Hola, 
cuando para distintos capítulos, la misma serie tiene distintos géneros para cada uno, se dice que la serie tiene distintos géneros(1)? ¿o que simplemente los géneros corresponden a los capítulos(2)? 

Si (1) fuese cierto,

- Entonces, entiendo que tenemos distintos géneros "incrustados" en los capítulos de cada serie y debemos "recuperarlos" buscando dentro de cada uno para saber todos los géneros (del macrogénero, del que se habló en la issue [123](https://github.com/IIC2413/Syllabus-2021-2/issues/123)) de una serie

Si (2) fuese cierto, 

- ¿entonces a una serie no le corresponden directamente los géneros? ¿o se entiende que si una serie tiene un capítulo de x género, entonces x género también corresponde a la serie misma?

- Por otro lado, nos pasó que Naruto Shipudden (fila 257 y 260 de multimedia.csv) tenía distintos géneros para un mismo capítulo (todos los atributos iguales menos género), ¿eso significaría que el capítulo tiene más de un género?

**Comment by arpincheira** [comment]
Hola, se que es poco práctico pero les contestaré con preguntas que recomiendo que analicen:
¿Si agrupan todos los datos respectivos a cada capítulo de una serie estos poseen distintos géneros?
¿No será que los datos se ven así debido a la distribución en al que fueron presentados?

Recomiendo que ordenen los datos por capítulo y/o serie para que los puedan ver con mayor claridad y de ahí sacar conclusiones.
