### ISSUE TITLE
Entrega 2 Impar: Tipo de atributo

### ISSUE THREAD

**Issue by raibd** [IIC2413/Syllabus-2021-2#178]
Hola, en el enunciado aparece que se debe especificar el "tipo/dominio de cada atributo". ¿Con esto se refiere a si es un int, varchar, etc?
Gracias

**Comment by arpincheira** [comment]
Efectivamente, corresponde a declarar los tipos de los atributos. Recuerda que también deben denotar si son o no llaves primarias o foráneas.
