### ISSUE TITLE
General: Descargar la BBD en formato .sql y subirlas a Colab

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2413/Syllabus-2021-2#179]
Hola! por la facilidad que tiene colab para realizar consultas queria saber si existia alguna forma de descargar la base de datos del grupo para poder importarla para testear ahi las request o algo por el estilo.
Gracias

**Comment by benjavicente** [comment]
> para testear ahi las request o algo por el estilo

Solo para confirmar: ¿Te refieres a las consultas, cierto?

**Comment by conyfernandezt** [comment]
Muchas gracias Vicente! Era justo a lo que referia :)
