### ISSUE TITLE
Servidor Problema con comando ssh grupoxx@codd.puc.ing.cl

### ISSUE THREAD

**Issue by railira** [IIC2413/Syllabus-2021-2#18]
Hola! Al intentar conectarme al servidor sale el siguiente error:
ssh: connect to host codd.ing.puc.cl port 22: Resource temporarily unavailable
Desconozco que puede ser lo que esté evitando la conexión.

**Comment by arpincheira** [comment]
Hola, ayer hubo un corte de luz programado en la universidad por lo que los servidores se encontraban deshabilitados, ahora debería estar funcionado correctamente
