### ISSUE TITLE
Entrega 2 Impar: Error al correr la página de PHP

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2413/Syllabus-2021-2#181]
Hola! Cuando trato de correr el proyecto en internet, me arroja este error. La verdad es que nunca lo había hecho, es más, trabajé en la mañana viendo la página y ahora no funciona. ¿Saben qué se podría hacer para solucionarlo? Gracias!!
[](url)
<img width="1134" alt="Captura de Pantalla 2021-10-12 a la(s) 21 12 01" src="https://user-images.githubusercontent.com/80789536/137045784-b0d29712-da8a-454e-8778-db9792ef3b7b.png">

**Comment by fernandosmither** [comment]
No soy ayudante pero tu página si me corrió con [este link](http://codd.ing.puc.cl/~grupo1/)
![image](https://user-images.githubusercontent.com/66154723/137047063-7bfc4b9f-0b70-4e39-8f6e-bb8881f471fd.png)

De paso te pregunto ya que funcionan tus consultas, ¿Crearon la base de datos desde 0 populándola con el csv de ejemplo, o simplemente pegaron los archivos y les funcionó?

**Comment by fernandolalanne** [comment]
Hola, en verdad ni idea que pasó pero ahora corre xD????. Muchas gracias! En cuanto a las tablas, para que te funcione la ayudantía debes crear en tu base de datos, en mi caso es grupo1e2, una tabla y poblarla con el cdv de los pokemones. Recién ahí te va a funcionar.
