### ISSUE TITLE
Entrega 2 Impar Apartado 2.1 : Proveedores de contenido que visualizaron los usuarios

### ISSUE THREAD

**Issue by minsoos** [IIC2413/Syllabus-2021-2#183]
Hola.
Teníamos entendido que el contenido (película o serie) que visualizaban los usuarios debía tener asignado un proveedor, pero no lo encontramos, ¿puede ser que falte? ¿o que simplemente no importe?
Gracias de antemano,

**Comment by fernandosmither** [comment]
> Hola, toda la información necesaria ya ha sido entregada. Fuera de esto, recomiendo revisar las tablas que fueron entregadas con el objetivo de contestar tu duda.

Estaba revisándolo y como visualizaciones solo relaciona un usuario a una serie/pelicula, si este usuario está en netflix y amazon que ambos dan la película "X", cómo podré saber en qué plataforma lo vio?
