### ISSUE TITLE
General: PDOException en PHP local - driver de pgsql no encontrado

### ISSUE THREAD

**Issue by jorgemouat** [IIC2413/Syllabus-2021-2#187]
>Hola, al intentar relizar una consulta en la página me tira este error, vi el data.php y tengo mis datos metidos correctamente. Gracias por cualquier ayuda!!
![image](https://user-images.githubusercontent.com/62305130/137067036-efc890a9-4b27-4c2c-8ede-54ea9dc1fb2d.png)

**Comment by jorgemouat** [comment]
Ya perfecto, ahora me tira un error de time out y supongo que es por no tener los archivos en WSL. Como los puedo mover y trabajar desde ahí? Gracias
![image](https://user-images.githubusercontent.com/62305130/137144377-27d0c29c-543e-4a16-8a1f-f3c1422fdd5b.png)

**Comment by benjavicente** [comment]
Creo que eso se debe a que el servicio de PostgreSQL no se ha iniciado, prueba con

```bash
sudo service postgresql start
```

Si quiere mover el directorio a WSL, tienes que hacer algo de este estilo:

```bash
mkdir ~/cursos # crear una carpeta para dejar mas ordenado los archivos que tengas en WSL (puede ser otro nombre)
mv /mnt/c/Users/cokem/Escritorio/6to_semestre/BDD/E2/Example-app ~/cursos
# Ojo que ahora el directorio no es parte del sistema de archivos de windows, en Windows 10 se puede hacer
# algo para verlos en el explorador de archivos, pero no es recomendado https://superuser.com/a/1495497

# Si tienes VSCode, probablemente puedas abrirlo en ese directorio sin problemas con
code ~/cursos
```
