### ISSUE TITLE
Entrega 2 Par Apartado X: Sobre BCNF

### ISSUE THREAD

**Issue by scavagnaro** [IIC2413/Syllabus-2021-2#188]
Hola!

Si tengo una entidad tal que tiene los siguientes atributos:
ID, Nombre, atributo que depende del nombre.

Se que no es BCNF, porque el Nombre no es Super key, pero el atributo depende de este. ¿Me conviene igual usar ID?

**Comment by arpincheira** [comment]
Hola, te recomiendo que veas la issue #151 en donde se responde una duda muy similar
