### ISSUE TITLE
Entrega 1 Par Apartado 2.1: Poblando las tablas

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2413/Syllabus-2021-2#19]
Hola!

Al momento de poblar las tablas, ¿Debemos crear nosotros tuplas "falsas" o nos debemos basar en algún archivo creado por ustedes?,

Gracias!

**Comment by benjavicente** [comment]
Hola! En esta entrega tienen que crear ustedes los datos, solo para que las consultas puedan arrojar resultados.
