### ISSUE TITLE
Entrega 2 Impar: Formato entrega resultados consultas

### ISSUE THREAD

**Issue by rfigueroa314** [IIC2413/Syllabus-2021-2#190]
> Hola, en la consulta 3 nos piden entregar todas las peliculas y/o series que tengan un cierto titulo, y como no se especifica que atributos hay que entregar de las peliculas y/o series, se asume que son todos. Pero en este caso peliculas y series tienen distintos atributos, por lo que no se podría mostrar en una misma tabla. Por lo tanto, que atributos hay que mostrar. 
Aprovecho de extender esta pregunta a las demas consultas, en todas las consultas que se nos piden mostrar peliculas o series, tenemos que mostrar todos sus atributos (incluyendo genero) o basta con el nombre?.

**Comment by arpincheira** [comment]
Hola, existen dos maneras de manejar esto:
- Que en la página web se entreguen dos tablas, una para series y otra para películas.
- Que se muestren los atributos en común de ambas tablas.

En el caso de tomar la primera opción deben entregar la consulta total y la subdivisión realizada en el código(para poder revisarlas con detalle y cumplir con lo solicitado).
