### ISSUE TITLE
Entrega 2 Impar Apartado 2.3 : apóstrofes en atributos de strings en relaciones

### ISSUE THREAD

**Issue by minsoos** [IIC2413/Syllabus-2021-2#195]
Hola, 
nos dimos cuenta que, específicamente la tabla películas tiene apóstrofes en los nombres de las películas, por ejemplo. ```She's Out of My League``` en la fila 42. Queríamos saber si esto podría afectar a las comillas simples que debemos ponerles a los strings para subirlos en la importación de datos.
Saludos,

**Comment by arpincheira** [comment]
Hola, efectivamente existen datos con comillas simples entre aquellos entregados con el objetivo de "dificultar" un poco el trabajo con estos, en lo personal les recomiendo tomar un pequeño grupo de datos y probar aquello que proponen como "posible problema" con el objetivo de ver si sucede aquello que mencionan y, en el caso de que suceda, ver como solucionarlo.(pueden probar en local o con tablas temporales en el servidor)

**Comment by minsoos** [comment]
Gracias
