### ISSUE TITLE
Entrega 2 Par Apartado X: Permiso denegado para ingresar a la página de la entrega.

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2413/Syllabus-2021-2#196]
Hola!

Al intentar ingresar a la página de la entrega con el link [Grupo 72](http://codd.ing.puc.cl/~grupo72/index.php) me entrega el siguiente error:

![imagen](https://user-images.githubusercontent.com/80288266/137222005-96759778-bd69-4769-8b7c-0f858bbc7e08.png)

¿Como podría solucionarlo?

Gracias.

**Comment by benjavicente** [comment]
Hola! Probablemente sea un tema de permisos que tiene el archivo `.php`. Prueba corriendo lo siguiente en bash:
```bash
chmod 755 path/al/archivo.php
```
La [guía de UITS tiene información clara al respecto](https://kb.iu.edu/d/abdb#change).
