### ISSUE TITLE
Item 1.3 : Por qué se incluye fecha? + 1 detalle

### ISSUE THREAD

**Issue by fernandosmither** [IIC2413/Syllabus-2021-2#2]
Por qué se filtra además de que tenga el mismo código, que tenga la misma fecha?
![image](https://user-images.githubusercontent.com/66154723/131188317-9e541a3f-32e3-42fb-8a88-7b1c2a1ab394.png)

Y el detalle, el enunciado pide el nombre, entonces no debería ser una proyección sin el nick y solo el nombre?

**Comment by hlarrainq** [comment]
Hola!

Cuando se hace el Join entre Partida y Juego, en las condiciones buscamos que para cada Partida, haya solo un Juego por Jugador. Los atributos que comparten estas tablas son el código de sala y la fecha, por lo que no usar la fecha (por ejemplo) podría provocar que un jugador quede registrado como si hubiera jugado más veces en distintas fechas sin haberlo hecho.

Por otro lado, respecto al primer detalle que mencionas, es correcto que el enunciado pide el nombre, por lo que lo estrictamente correcto es devolver solo la proyección del nombre, pero para efectos de la resolución del ejercicio no hay problema en devolver el nick también.

En el segundo detalle de la pregunta g), es más de lo mismo. No se especifica qué atributo devolver en el enunciado, pero con entregar el nick, el nombre o la tupla es suficiente.

**Comment by fernandosmither** [comment]
> Hola!
> 
> Cuando se hace el Join entre Partida y Juego, en las condiciones buscamos que para cada Partida, haya solo un Juego por Jugador. Los atributos que comparten estas tablas son el código de sala y la fecha, por lo que no usar la fecha (por ejemplo) podría provocar que un jugador quede registrado como si hubiera jugado más veces en distintas fechas sin haberlo hecho.
> 
> Por otro lado, respecto al primer detalle que mencionas, es correcto que el enunciado pide el nombre, por lo que lo estrictamente correcto es devolver solo la proyección del nombre, pero para efectos de la resolución del ejercicio no hay problema en devolver el nick también.
> 
> En el segundo detalle de la pregunta g), es más de lo mismo. No se especifica qué atributo devolver en el enunciado, pero con entregar el nick, el nombre o la tupla es suficiente.

Hola,

Igual sigo con la siguiente duda, 
![image](https://user-images.githubusercontent.com/66154723/131235559-9a80ecc3-d4b2-435f-a921-8af208a62151.png)

"Código" es una columna originalmente de sala que estamos usando como primary key, y como tal podemos asumir que no habrán códigos de salas repetidos.

Pasa que en la e) piden solamente el nombre de los jugadores que hayan jugado alguna vez en el mapa con ese nombre, y por lo que tengo entendido aunque las fechas no cuadren, 1) No deberían ligarse jugadores con mapas que no les corresponden si les hago un join por el código y 2) Si hago una proyección final de nombre por propiedades de tuplas no deberían haber repeticiones, o sí?

adjunto la consulta que hice originalmente.
![image](https://user-images.githubusercontent.com/66154723/131235688-7262de4c-47bd-49f6-af4d-fc0652c68c41.png)

**Comment by hlarrainq** [comment]
> "Código" es una columna originalmente de sala que estamos usando como primary key, y como tal podemos asumir que no habrán códigos de salas repetidos.

Esto es correcto.

>  1) No deberían ligarse jugadores con mapas que no les corresponden si les hago un join por el código

Asumiendo que cada **juego** mantiene su mapa siempre independientemente de la fecha, esto es correcto, el resultado no cambiaría. Sin embargo, si es que un **juego** con un mismo código de sala cambia de mapa en una fecha distinta, se podría vincular un jugador que jugó con ese código de sala, pero no en ese mapa (pues lo hizo en un día distinto). Por esto es una mejor práctica usar los dos atributos.

>  2) Si hago una poyección final de nombre por propiedades de tuplas no deberían haber repeticiones, o sí?

No hay repeticiones, pues en algebra relacional hablamos de conjuntos. No pueden haber duplicados.

**Comment by fernandosmither** [comment]
> > "Código" es una columna originalmente de sala que estamos usando como primary key, y como tal podemos asumir que no habrán códigos de salas repetidos.
> 
> Esto es correcto.
> 
> > 1. No deberían ligarse jugadores con mapas que no les corresponden si les hago un join por el código
> 
> Asumiendo que cada **juego** mantiene su mapa siempre independientemente de la fecha, esto es correcto, el resultado no cambiaría. Sin embargo, si es que un **juego** con un mismo código de sala cambia de mapa en una fecha distinta, se podría vincular un jugador que jugó con ese código de sala, pero no en ese mapa (pues lo hizo en un día distinto). Por esto es una mejor práctica usar los dos atributos.
> 
> > 1. Si hago una poyección final de nombre por propiedades de tuplas no deberían haber repeticiones, o sí?
> 
> No hay repeticiones, pues en algebra relacional hablamos de conjuntos. No pueden haber duplicados.

Ahora me quedó claro, gracias!
