### ISSUE TITLE
Entrega 1 Par Apartado Videojuegos: Fechas en los pagos mensuales

### ISSUE THREAD

**Issue by cadaeic314** [IIC2413/Syllabus-2021-2#20]
Sobre los pagos mensuales, tengo la duda de si es necesario agregar la fecha de pago de la suscripción. Me surge la duda porque tendríamos problemas en nuestro modelo si se añade la fecha, ya que ambos tipos de pago los modelamos en la misma relación pero con un atributo que indica que tipo es cada cual. Al final, mi duda también puede entenderse en el sentido de si existe alguna diferencia a destacar entre los pagos mensuales y los únicos, como la fecha del pago mensual, por ejemplo.

**Comment by arpincheira** [comment]
Hola, la idea principal es que ustedes lleven el registro de uso de la cuenta del usuario, puedes pensarlo como un registro de transacciones y, por otra parte, las subscripciones que ha tenido en el tiempo.

Un ejemplo de esto puede ser que un servicio de subscripción mensual tenga un costo de X y que el usuario contrate Y meses, por lo que la transacción sería única y tendría un valor de XY y tendría un registro histórico o algo por el estilo.

**Comment by cadaeic314** [comment]
Muchas gracias, ahora si comprendo :)
