### ISSUE TITLE
Servidor [Problema/Duda] con Filezilla

### ISSUE THREAD

**Issue by emiliaup** [IIC2413/Syllabus-2021-2#200]
Hola! estoy teniendo problemas al conectar mi php con mis tablas y el centro de mi problema es FileZilla. Antes podía conectarme con FileZilla con 
host: codd.ing.puc.cl username: grupo37 pasword: ... port: 80.
 Usando el port 80 tuve un problema, no se podia conectar con mis tablas. De ahí me di cuenta que uno debe de ocupar el port 5432 pero con este puerto tengo un error más grande, ni siquiera se me conecta. No se que hacer. Porfa help
![image](https://user-images.githubusercontent.com/69696514/137238313-475549c9-2b63-4ef6-903f-7cc185210c12.png)

**Comment by arpincheira** [comment]
Hola, el puerto es 22.
