### ISSUE TITLE
Entrega 2 Impar Apartado web: Como puedo ejecutar la pagina desde un localhost?

### ISSUE THREAD

**Issue by Icarus328** [IIC2413/Syllabus-2021-2#209]
Hola, tengo la duda de como puedo ejecutar la pagina desde un localhost para no tener que cambiar los archivos a sites cada vez que hago un cambio, no me quedo demasiado claro en la ayudantía.

Gracias!

**Comment by arpincheira** [comment]
Hola, para poder ejecutar la página desde un localhost debes tener postgresql y php(5.4 o posterior) instalados en tu computadora. Una vez los tengas te recomiendo visitar estos dos sitios para poder ver como correr el servidor de forma local y las distintas opciones que tienes para el mismo:

- https://www.php.net/manual/en/features.commandline.webserver.php
- https://www.php.net/manual/en/features.commandline.options.php
