### ISSUE TITLE
Entrega 1 Par Apartado Preórdenes: Beneficios de por vida al hacer una preorden

### ISSUE THREAD

**Issue by cadaeic314** [IIC2413/Syllabus-2021-2#21]
Sobre los beneficios de por vida en las preórdenes, me gustaría a que tipos de beneficios se refiere. Por ejemplo:

- Si el videojuego DCCyberpunk aún no está a la venta y las preventas del juego están disponibles. 

¿Un beneficio podría ser una skin exclusiva que solo se dará por esa ocasión junto con la compra de la preorden y nunca más?, al final me refiero a si es algo tan específico como eso o los beneficios pueden ser más generales y repetirse entre preórdenes (o una mezcla de ambas también en una de esas).

**Comment by arpincheira** [comment]
Hola, la idea de los beneficios es describir de forma breve algún tipo de compensación que da el videojuego por hacer dicha pre-orden.  Por lo tanto, puede ser algo bastante genérico como "skin exclusiva" o "montura exclusiva" y no es necesario ahondar con mucho más detalle en esta.(como decir que nunca más se va a dar)

**Comment by cadaeic314** [comment]
Muchas gracias 😄
