### ISSUE TITLE
Entrega 2 Impar Apartado X : Error Encoding

### ISSUE THREAD

**Issue by lucasilabaca** [IIC2413/Syllabus-2021-2#210]
Hola!  Al intentar poblar las tablas me da el error:  ERROR:  invalid byte sequence for encoding "UTF8": 0xf1 0x6f 0x2c 0x67

¿Cómo puedo solucionarlo?  Gracias!

**Comment by benjavicente** [comment]
Hola! Prueba lo mencionado en la issue #65, si no funciona me cuentas.

**Comment by lucasilabaca** [comment]
Ok, lo probaré, avisaré si persiste el problema, muchas gracias!
