### ISSUE TITLE
Entrega 2 Impar Apartado Diagrama : Qué tan descriptivas pueden ser las relaciones?

### ISSUE THREAD

**Issue by fernandosmither** [IIC2413/Syllabus-2021-2#211]
En el diagrama las relaciones deben ser solo una palabra, ejemplo: "tiene" o puede ser por ejemplo:

A - Tiene género - Género
|
Tiene Subgénero - Subgénero

Donde en las relaciones en vez de solo poner un  verbo como "tiene", especifico a la entidad que conecta, y lo conecto con la entidad?

**Comment by arpincheira** [comment]
Si, normalmente recomendaría no utilizar el mismo nombre para las relaciones pero si se puede dar que se repita el mismo nombre en el diagrama E/R. 

Ahora, como **tip** recomiendo ver la issue #123 de todas formas por el tema de géneros y subgéneros.
