### ISSUE TITLE
Entrega 2 Impar Apartado 2.3 : duda sobre query de numero de temporadas

### ISSUE THREAD

**Issue by Diegothx** [IIC2413/Syllabus-2021-2#213]
Para esta parte se nos pide devolver todas las series con las temporadas indicadas. Mi duda es si esto se refiere a todas las temporadas que se tenga por lo menos un capitulo en la base de datos, o a la temporada de mayor numero conocida
Ejemplo: si tubieramos una serie con solo un capitulo en la db, y este capitulo fuera de la temporada 3, entonces consideramos que esta serie tiene 3 temporada o 1?

**Comment by arpincheira** [comment]
Hola, se refiere a que tengan al menos n temporadas en la base de datos, esto es independiente del número de episodios de la misma. En el caso que preguntas, dado que es solo una temporada la que se encuentra registrada en la base de datos(independiente del número de esta), se debe considerar que dicha serie tiene solo una temporada
