### ISSUE TITLE
Entrega 2 Impar Apartado 2.3 : Normalizacion de datos

### ISSUE THREAD

**Issue by isinahum** [IIC2413/Syllabus-2021-2#215]
Hola!

En la normalización de datos y al crear nuestros archivos .csv "utiles", ¿podemos mezclar información de dos tablas distintas para crear otra? Ej. Hacer un peliculas.csv que mezcle la info que esta en multimedia (filtrando lo de series) y agregando los subgéneros? ¿O al "normalizar" los datos solo podemos eliminar columnas y filas?

**Comment by isinahum** [comment]
Claro, pero me refiero a hacer:

pid, titulo, claisificacion ..... , Drama;Suspenso;Comedia, Apocaliptico;Cyberpunk;,Biopunk

Estaría bien tener una tabla en los archivos .csv así? Como haber manipulado los datos de esa forma?

**Comment by arpincheira** [comment]
Hola, no te puedo contestar eso pero te tengo unas preguntas que te puede guiar un poco:

¿Qué pasaría si el día de mañana quisieras añadir un nuevo género?
¿Qué pasaría si quieres añadir un género a una de las películas?
¿Qué pasaría si te dicen que un género posee información adicional(como una descripción o algo por el estilo)?

Si la respuesta a estas preguntas requiere meterse en cada dato y modificarlo entonces probablemente existe un error de diseño no menor. Lo mismo ocurre en el caso de que quieras almacenar esta nueva información por cada película que posee dicho género.
