### ISSUE TITLE
Entrega 1 Par Apartado Consultas: ¿Como se interpretan los subgéneros?

### ISSUE THREAD

**Issue by Pabloski100** [IIC2413/Syllabus-2021-2#22]
Hola, en la consulta 3 me surgió una duda sobre como se interpretan los subgéneros. Por decir un ejemplo, en películas, el subgénero terror psicológico es también una película de terror, entonces, también podría buscar películas de terror psicológico buscando solo películas de terror. En la consulta ¿Es valido buscar subgéneros solo por el genero? Supongo que depende de como se definan las tablas, es solo que por como las construimos creo que podríamos hacerlo así en mi grupo.

**Comment by victoriatsimoyannis** [comment]
> Hola!
> 
> En la consulta 3 te piden mostrar los nombres de los juegos que pertenecen a un género o a un subgénero de este. Ojo que la única variable que te entregan es el género **FPS**, por lo tanto, se espera que busquen esto utilizando solo el nombre del género.

Hola!
 Entonces se espera que en la consulta solo nos preocupemos del género? o qué de alguna forma con el nombre del género podamos llegar a los subgéneros? No entendí muy bien eso.

**Comment by hebusch** [comment]
Tu base de datos tiene que estar modelada de forma que teniendo el nombre del género puedas acceder también a los subgéneros de este

**Comment by victoriatsimoyannis** [comment]
> Tu base de datos tiene que estar modelada de forma que teniendo el nombre del género puedas acceder también a los subgéneros de este

habría que hacer como otra tabla entonces que relacione eso?

**Comment by hebusch** [comment]
No te puedo decir como hacerlo pues depende de tu modelo pero sí, esa sería una forma correcta de modelarlo
