### ISSUE TITLE
Extensión plazo de entrega 2 proyecto

### ISSUE THREAD

**Issue by graci007** [IIC2413/Syllabus-2021-2#221]
Hola!,
realmente me preocupa la lentitud del servidor con la que esta funcionando, lo cual ha hecho perder tiempo en poder seguir trabajando, además considerando que las fechas de entregas del departamento están realmente juntas y  que la semana de receso técnicamente comienza el próximo lunes, creo que seria una buena idea poder dar una extensión de plazo ojala hasta el domingo, por temas de salud mental, el extender la entrega para el fin de semana dejaría la opción abierta de poder arreglar detalles o poder darse un descanso para trabajar de manera correcta, espero que enserio puedan considerar esta solicitud, que tengan buen fin de semana.

**Comment by QuestionMyLife** [comment]
La semana de receso comienza el lunes, tener plazo hasta el domingo es lo justo u.u

**Comment by juansegmart** [comment]
Sí, por favor.
Todas las entregas están para hoy 😭

**Comment by psostin** [comment]
Me sumo a la solicitud!

**Comment by lpalacios1** [comment]
Me sumo a la solicitud

**Comment by Mrsolis** [comment]
Me sumo a la solicitud!

**Comment by danvillablanca** [comment]
Me sumo a la solicitud!

**Comment by MaxBrinck** [comment]
Me sumo a la solicitud, siempre nos cargan durisimo antes del receso, porfavor den plazo hasta el domingo o porlomenos hasta mañana !

**Comment by ercaceres** [comment]
Me sumo a la solicitud
