### ISSUE TITLE
Entrega 2 Impar Apartado 2.4 : Proyectar tabla entera.

### ISSUE THREAD

**Issue by Icarus328** [IIC2413/Syllabus-2021-2#226]
Hola, quería saber si lo de "Si no se especifica la entidad a proyectar, proyecte la tabla entera" todavía corre.

**Comment by arpincheira** [comment]
Efectivamente, hay solo algunos casos para los grupos impares(ver issue #190) en donde no necesariamente ocurre pero en su mayoría deberían proyectar toda la entidad.
