### ISSUE TITLE
Entrega 2 Impar Apartado 2.4 : Consulta en PHP no recibe la variable de campo

### ISSUE THREAD

**Issue by raimundosilvac** [IIC2413/Syllabus-2021-2#228]
Hola! Al realizar las consultas 3 y 5, en la página no está considerando la variable entregada, mientras que , si definimos un valor fijo para el atributo dentro de la consulta, se genera correctamente y nos entrega la tabla que queremos. No entendemos por qué pasa esto, siendo que en la consulta 2, sí considera la variable asociada a la cantidad de temporadas.
En código, cuando no nos da resultado sería algo más o menos así:
`$username = $_POST['username'];`
`$query = "SELECT * FROM usuarios WHERE username = $username;";`

Y cuando si nos da resultado es cuando comparamos un atributo definido en la misma consulta. Esto sería:

`$query = "SELECT * FROM usuarios WHERE username = 'usuario123';";`

**Comment by benjavicente** [comment]
Hola! Ve cuál es el valor que tiene `$query` en el primer caso (utilizando `echo`), para verificar que realmente está bien insertado el `$username` en la consulta SQL. Probablemente algo falte o algo insertado rompe la consulta (para lo último puedes ver la issue #198 donde se explica como solucionarlo).

**Comment by raimundosilvac** [comment]
Gracias con lo del `echo` funcionó!
