### ISSUE TITLE
Entrega 2 Par Apartado 2.3: videojuegos con pago por suscripcion no tienen espeficado proveedor

### ISSUE THREAD

**Issue by cadaeic314** [IIC2413/Syllabus-2021-2#229]
Tengo una duda respecto a los videojuegos con pago por suscripción, ya que revisé algunos y a ninguno se le especifica proveedor (o por lo menos no lo encontré en ninguna tabla). Por ejemplo, el pago con id 2348 está asociado a la suscripción con id 244 y, a su vez, esta está relacionada con el videojuego de id 9730. Pero en ninguna parte se especifica el proveedor, y en la tabla de proveedores este juego está relacionado con todos los proveedores. 

¿Qué se hace en estos casos?, ¿asumimos que no tiene proveedor y lo dejamos null o hay otra forma de obtener el proveedor en las tablas?

Muchas gracias de antemano.

**Comment by arpincheira** [comment]
Hola, eso se dijo en la issue #85
