### ISSUE TITLE
Entrega 1 Impar Apartado 1 : Duda con interpretación de proveedores

### ISSUE THREAD

**Issue by mariizamb** [IIC2413/Syllabus-2021-2#23]
> Hola! Mi duda consiste en:
En la sección de proveedores se indica que el proveedor X según el plan ofrece películas Y, Z por ejemplo. La confusión que existe en mi grupo es que no sabemos si este plan es de un mismo proveedor (1) o es de acuerdo distintos proveedores (2), es decir,
1. proveedor X tiene el plan 1, 2, 3 con distintas películas de acuerdo al plan ofrecido y luego proveedor A tiene planes 4,5,6 con otras películas en según el plan.
o
2. proveedor X ofrece películas Y,Z y proveedor A ofrece solo Z como película.
Espero se entienda la duda, 
Graciass
Saludos!

**Comment by arpincheira** [comment]
Hola, las películas ofrecidas por un proveedor son siempre las mismas, por lo que es correcto asumir que existe un único plan de subscripción por proveedor o que, aunque lo modelen con más de un plan de subscripción, las películas en sí no van a variar siempre y cuando el proveedor no varíe.

Un ejemplo puede ser que Netflix tenga 3 planes de subscripción con distintos precios y números de espectadores simultáneos pero que en los planes 1,2 y 3 siempre se van a tener las mismas películas a disposición
