### ISSUE TITLE
Guia 2 Pregunta 4

### ISSUE THREAD

**Issue by Gjescalante** [IIC2413/Syllabus-2021-2#24]
Hola! esta pregunta me dio problemas en el collab porque dice que consume toda la ram XD, que hice de malo? 
![image](https://user-images.githubusercontent.com/48481711/132587967-1e3d8b72-50c9-4595-a7c4-c9db0db12973.png)

**Comment by hebusch** [comment]
Hola! te faltan las restricciones para unir las 3 tablas, es decir, igualar las primary keys de las tablas con sus foreign respectivos.
