### ISSUE TITLE
Guía 2 : No puedo cargar el colab

### ISSUE THREAD

**Issue by fernandosmither** [IIC2413/Syllabus-2021-2#25]
Desde que se acabó el horario de lab no he podido cargar el colab de nuevo.

Todo funcionaba al principio, hasta que intenté hacer un triple producto cruz sin restricción y eso hizo overflow de ram lo que me reinició el colab, pero cuando ejecuto la primera celda, me tira un error. For good meassure, creé un  colab completamente nuevo y subí de nuevo el ipynb, pero nada. Adjunto foto del error

![image](https://user-images.githubusercontent.com/66154723/132590222-bbc8d719-0eee-449a-830c-93b941cbe9e9.png)

Saludos!

**Comment by benjavicente** [comment]
Hola! Probaste si funcionaba luego de restablecer el entorno de ejecución?

```rb
Entono de ejecución -> Restablecer la configuración de fábrica del entorno de ejecución
```
