### ISSUE TITLE
Entrega 1 Par Crear Tablas: Para la tabla de proveedores

### ISSUE THREAD

**Issue by lopez2000** [IIC2413/Syllabus-2021-2#26]
Al agregar los juegos que ofrece el proveedor, se puede hacer un set o algo por el estilo? o hay que hacer varias veces el mismo proveedor con distintos juegos asociados (Si es así, como se hace para que se pueda repetir el primarykey del proveedor).

Muchas gracias.

**Comment by arpincheira** [comment]
Hola, te recomiendo investigar sobre foreing keys y sobre tablas intermedias, al hacerlo probablemente vas a poder encontrar la respuesta a tu pregunta
