### ISSUE TITLE
Guia 2: Pregunta 3 (SQL Avanzado), no entiendo orden

### ISSUE THREAD

**Issue by Pabloski100** [IIC2413/Syllabus-2021-2#27]
Hola, intente hacer esa pregunta pero no entiendo bien el orden, ¿pide una tabla con cada columna en un orden distinto o  es solo una columna ocupando los varios ordenes que piden como desempates?

**Comment by hlarrainq** [comment]
Hola!
Se pide una tabla en la que las filas estén ordenadas por los atributos mencionados, y en caso de empates se utiliza el atributo con menor prioridad para ordenar.
En este caso primero se ordena por calificación, en caso de que más de uno tengan la misma nota se ordenan por nombre, y en caso de que dos tengan el mismo nombre se ordena por año. Esto lo puedes hacer usando ORDER BY y agregando luego los atributos en orden de prioridad.
