### ISSUE TITLE
Feedback Entrega 2

### ISSUE THREAD

**Issue by xDanman** [IIC2413/Syllabus-2021-2#277]
Hola! Quería consultar si es que los comentarios sobre la corrección de la entrega 2 están completos o si es que faltan ayudantes que aún están colocando los comentarios. 

Tengo esta duda ya que no todos los puntos en los que se me resto puntaje están justificados.

Gracias!

**Comment by arpincheira** [comment]
Hola, en el caso de que tengas problemas con respecto a la corrección te recomiendo fuertemente mandar una solicitud indicando que falta justificación en un respectivo campo y que te gustaría saber el motivo.

**Comment by xDanman** [comment]
Con solicitud te refieres a recorrección?

**Comment by arpincheira** [comment]
Sí
