### ISSUE TITLE
Varias dudas con el enuncionado de la Entrega 1 grupo impar

### ISSUE THREAD

**Issue by Icarus328** [IIC2413/Syllabus-2021-2#28]
Hola, tengo varias dudas con respecto a lo que se pide en el enunciado de la entrega 1 para grupos impares en el proyecto.

1) A la hora de "Contenido visualizado" solo se consideran capítulos y películas? o también temporadas? 
Por ejemplo, solo un capitulo de una serie puede tener el tic de "visualizado" pero no una temporada o la serie entera?

2) El precio de arrendar una película es constante o puede variar de película a película, de proveedor a proveedor?

3) El tiempo de arrendar una película es constante o puede variar de película a película, de proveedor a proveedor?

4) Las películas solo pueden tener un genero o pueden tener más de un genero? (sin contar subgéneros)

5) En subgéneros, a que corresponde un "subgénero de ciencia ficción"? Es decir, que la película tiene, de genero "Acción" y subgénero "ciencia ficción" o la película tiene de genero "ciencia ficción" y de subgénero "distopía" por ejemplo?

6) Una película tiene puede tener más de un subgénero?

7) En la primera query, donde se pide "Muestre todas las películas y todos los proveedores que las ofrecen" Se refiere a que tengo que mostrar el titulo de la película junto a su proveedor, o mostrar todos los datos de la película (id, titulo, puntuación, etc.) en conjunto del proveedor?

**Comment by arpincheira** [comment]
Hola, las respuestas son las siguientes:

1. Sí, solamente capítulos y películas
2. Puede variar de película a película **y** de proveedor a proveedor
3. Puede variar por proveedor **y** por película
4. Pueden tener uno o más géneros
5. Lo segundo que mencionas
6. Efectivamente puede tener más de un subgénero
7. Debes entregar ambas entidades enteras, es decir, todos los atributos de los proveedores y todos los atributos de los proveedores(esto haciendo referencia al apartado en donde  se dice que, en el caso de no especificar atributo a mostrar, deben mostrar toda la entidad)

**Comment by chubretovic** [comment]
Con respecto al punto 7, en caso de que debamos proyectar la entidad entera, usando álgebra lineal, podemos usar el asterísco? Por ejemplo, para mostrar la identidad X, podemos hacer pi_X.* o debemos escribir cada atributo?

**Comment by arpincheira** [comment]
Hola, deben escribir cada atributo, aunque pueden hacer un apartado en el que muestren símbolos e indiquen los atributos a los que corresponden. (En SQL si pueden usar el .*)

**Comment by chubretovic** [comment]
Perfecto. Y con respecto al punto 5, podemos asumir que si una película tiene como subgénero uno derivado de ciencia ficción, es porque tiene con género a ciencia ficción, o se espera que hagamos una tabla de cada género con sus subgéneros y corroboremos de que el subgénero es efectivamente subgénero de ciencia ficción.

**Comment by arpincheira** [comment]
Se espera que corroboren que el subgénero efectivamente es de ciencia ficción(lamento la demora en contestar esta duda)
