### ISSUE TITLE
Contenidos Control 3

### ISSUE THREAD

**Issue by nvaldiviesoo** [IIC2413/Syllabus-2021-2#281]
Hola!
¿Qué contenidos serán evaluados específicamente en el control 3 de la próxima semana? 
(Me disculpo si ya se avisó, pero no logré encontrar esa información en ninguna parte 😅 )
Saludos

**Comment by ironcadiz** [comment]
Hola!
El control será de las últimas 2 clases. Data science y mongo db

**Comment by nvaldiviesoo** [comment]
Ok! Muchas Gracias!
