### ISSUE TITLE
Entrega 1 Par Apartado Consultas:  Se puede usar sum() en algebra relacional?

### ISSUE THREAD

**Issue by aiherrera1** [IIC2413/Syllabus-2021-2#29]
Hola tenia la duda si es que se puede usar sum(columna)=3 como una condición para una consulta en álgebra relacional .

**Comment by rieg-ec** [comment]
Hola @aiherrera1!

Si, en algebra relacional existe la función `sum`, asi que puedes usarla. Te dejo unas slides que encontré donde explican más en detalle cómo se usa (p. 8)

http://users.cms.caltech.edu/~donnie/cs121/CS121Lec03.pdf

**Comment by rieg-ec** [comment]
Ahora, ten en cuenta que esa funcion no opera sobre filas, sino sobre columnas, por lo tanto no puedes usarla como condicion por ejemplo en un select o un join.

**Comment by arpincheira** [comment]
Hola, corrigiendo el comentario anterior, **NO pueden** utilizar count en esta entrega, únicamente pueden utilizar lo visto en clases a menos de que sepan construir dicho operador a partir de los que se vieron.
