### ISSUE TITLE
Duda ayudantía 1

### ISSUE THREAD

**Issue by chubretovic** [IIC2413/Syllabus-2021-2#3]
Hola, espero que estén bien. Tengo un par de dudas con los contenidos de la ayudantía 1.
1. Si quiero renombrar sólo un atributo de una tabla, es necesario especificar que los demás atributos no serán cambiados? Por ejemplo, en el caso de la tabla Montañas, si quiero cambiar el atributo nombre para no confundirlo con el atributo nombre de la tabla Usuarios, es necesario hacerlo de la siguiente manera: ```rho((mid -> mid, nombre -> nombre montaña, calificación -> calificación, altitud -> altitud), Montañas)```, o se puede hacer ```rho((nombre -> nombre montaña), Montañas)```? 
2. Puedo renombrar una relación por segunda vez con el mismo nombre, es decir, puedo "actualizar una relación". Por ejemplo, en la diapositiva 68 de la ayudantía aparece un renombramiento de "GrahamNoMasAltas" y se le piden las proyecciones de todos los atributos de G1 para no guardar los de G2. En este caso, sería factible renombrar la selección de ```G1.altitud < G2.altitud(G1XG2)``` como "GrahamNoMasAltas" y después, actualizar la relación renombrando con el mismo nombre, solo que ahora pidiendo los atributos correspondientes a G1.

Saludos y gracias.

**Comment by conyortizsimpson** [comment]
Hola!
1. No es necesario que escribas todos los atributos, solo el que vayas a cambiar.
2. Si a lo que te refieres sería como una "sobreescritura" de la relación, cuando utilizas nuevamente un nombre que ya usaste antes se asume que pierdes la relación anterior y como relación queda la que pusiste al inicio.
Espero haya podido responder tu duda :)

**Comment by chubretovic** [comment]
Perfecto, muchas gracias.
