### ISSUE TITLE
Entrega 1 Par función count RA

### ISSUE THREAD

**Issue by MotxiGer** [IIC2413/Syllabus-2021-2#30]
En álgebra relacional (Pregunta 2.3)  se puede utilizar la función count()?

**Comment by rieg-ec** [comment]
Hola @MotxiGer 

Si, count() se puede usar. Ten en cuenta que como las otras funciones de agregación no opera sobre las filas 😄

**Comment by arpincheira** [comment]
Hola, corrigiendo el comentario anterior, **NO pueden** utilizar count en esta entrega, únicamente pueden utilizar lo visto en clases a menos de que sepan construir dicho operador a partir de los que se vieron.
