### ISSUE TITLE
2.1.2 : En cuanto al periodo.

### ISSUE THREAD

**Issue by joshelml** [IIC2413/Syllabus-2021-2#309]
Hola! cuando dice "queremos saber cuales son los artistas más importantes en el período"
se refiere a los 10 artistas que más aparecen en el ranking por año? (onda 10 artistas en el 2019, 10 artistas e el 2018, etc)

**Comment by ironcadiz** [comment]
No, en todos los datos.

**Comment by joshelml** [comment]
Entonces debo agrupar los datos por semana y ahi sacar los 10 aritstas por semana?

**Comment by ironcadiz** [comment]
No, hay que sacar los 10 artistas que mas hayan estado el ranking durante todo el periodo de los datos.
No es necesario que agreguen por fecha.
