### ISSUE TITLE
Entrega 1 Impar Apartado 1 : Parámetros Series: año y puntuación 

### ISSUE THREAD

**Issue by colobos** [IIC2413/Syllabus-2021-2#31]
Hola!!
Tengo una duda respecto a las series, específicamente al año y puntuación. ¿Se espera que estos valores dependan de la temporada en específico de la serie? Y con ello, ¿sería posible trabajar las temporadas de las series, como series independientes?

Saludos!

**Comment by arpincheira** [comment]
Hola, la idea es que el año y puntuación correspondan directamente a la serie y no a la temporada como tal. Ahora, con respecto a la segunda pregunta, piensa que las series poseen(puede que esta palabra sea importante) temporadas y estas últimas se componen como un conjunto de capítulos.

**Comment by colobos** [comment]
Entonces ¿el año representaría, el año de lanzamiento de la serie, y la puntuación, el puntaje general de esta?

**Comment by arpincheira** [comment]
En lo que respecta a esta entrega, si
