### ISSUE TITLE
Entrega 1 Par Apartado 1: [Duda Subscripción Videojuego]

### ISSUE THREAD

**Issue by cfernandek** [IIC2413/Syllabus-2021-2#32]
> Hola, tengo una duda acerca del enunciado de la Entrega 1. Mi duda es si la subscripción es para todos los videojuegos a la vez, o cada usuario se subscribe a cada videojuego por separado. Ejemplo: Un usuario que tiene una subscripción activa, esta subscripción es para una plataforma que contiene a todos los videojuegos, o el usuario se debe subscribir independientemente a cada videojuego. 

También tengo una duda si un videojuego se puede adquirir por solo pago único, por subscripción o gratis, solo por uno de estos métodos (onda Mario Kart es un juego que solo se puede adquirir por pago único). O puede obtenerse de cualquiera de las tres formas

**Comment by arpincheira** [comment]
Hola, te voy a poner un ejemplo: antiguamente  tanto Starcraft II como WoW contaban con un sistema de subscripción mensual en el que uno debía pagar al juego mismo a través de la plataforma de Blizzard la cual contaba adicionalmente con juegos como el Hearstone que era un juego gratuito. Ahora, como usuario uno podía elegir si es que jugaba alguno de los juegos con subscripción dichos anteriormente (y para ello pagar la subscripción de cada uno **por separado**) o si no jugaba ninguno de estos juegos y me dedicaba únicamente a jugar Hearstone (sin pagar nada). En resumen **se subscribe a cada juego por separado**.

Em... solo  puedes adquirir un videojuego por uno de los métodos  mencionados, ojo que un juego puede variar su precio por proveedor e incluso llegar a ser gratuito(**hint**).

**Comment by cfernandek** [comment]
Todo muy claro, muchas gracias.
