### ISSUE TITLE
Entrega 1 Par Apartado 1: [Duda Reseñas]

### ISSUE THREAD

**Issue by victoriaatria** [IIC2413/Syllabus-2021-2#33]
Hola!

Con respecto a las reseñas, los videojuegos ofrecidos por cada proveedor distinto son considerados únicos?

Por ejemplo si tengo Videojuego_1 que es ofrecido por Proveedor_1 y Proveedor_2, cuando alguien escribe una reseña sobre Videojuego_1, esta corresponde únicamente al Videojuego_1 ofrecido por Proveedor_1, o a todos los Videojuego_1 ofrecidos por cualquier proveedor?

**Comment by arpincheira** [comment]
Son independientes del proveedor.
