### ISSUE TITLE
Entrega 1 Par Apartado 1: Formato de Fechas

### ISSUE THREAD

**Issue by pablosbw** [IIC2413/Syllabus-2021-2#34]
Hola, quería saber si tenemos libertad para escoger el formato de fechas que mas nos acomode. Muchas gracias de antemano.

**Comment by arpincheira** [comment]
Hola, la idea es que elijan fechas "con sentido" pero inicialmente no vamos a ser muy estrictos con eso, yo les recomendaría que piensen en los pagos como "pagos en tiempo real", en donde si importa que cosa pago primero durante el mismo día(**hint**).

**Comment by piacabrera** [comment]
Hola! en qué momento piden guardar la fecha del pago? entendí por el enunciado que era solo una fecha de lanzamiento.
