### ISSUE TITLE
Entrega 1 Impar Apartado 1 : Duda con generos y Subgeneros

### ISSUE THREAD

**Issue by mariizamb** [IIC2413/Syllabus-2021-2#35]
> Hola! Lo que sucede es que no entiendo la parte de generos y subgeneros
Un subgenero debe depender netamente de un genero? 
o puede ser por ejemplo una pelicula con Genero acción subgenero comedia
y luego otra pelicula puede tener genero acción y subgenero comedia?
o un subgenero nunca se puede convertir en un genero, pero si pertenecer a varios generos?
Es decir, una pelicula con Genero acción, subgenero suspenso
y otra pelicula con genero Thriller y subgenero suspenso?

**Comment by arpincheira** [comment]
Hola, un subgénero efectivamente depende de un género, a continuación te presento un ejemplo:

La película "El Juego del Miedo"(SAW) se podría considerar como una película de los géneros Terror y Suspenso (también podría considerarse como policiaca pero dejemos eso a parte). Adicionalmente la película posee un subgénero indudable el cual corresponde a Gore, el cual es un subgénero de las películas de terror.

Del Mismo modo existen películas las cuales corresponderían a Comedia y podrían tener el subgénero de Comedia Romántica o cosas por el estilo.

Ahora, también se puede dar que exista un subgénero que se relacione con más de un género como "superhéroes" correspondiente a una mezcla de ciencia ficción y de acción.

Espero haber contestado tu pregunta

**Comment by mariizamb** [comment]
Súper! Graciass

**Comment by mariizamb** [comment]
última pregunta jaja, estos sub generos se asumen como conocidos?

**Comment by agustinmonti1** [comment]
> última pregunta jaja, estos sub generos se asumen como conocidos?

Tengo la misma duda! Cuales son los subgeneros de FPS?

**Comment by victoriatsimoyannis** [comment]
> última pregunta jaja, estos sub generos se asumen como conocidos?

Hola, tengo la misma duda! Hay que saber cuales son los subgeneros de FPS (para realizar la consulta) si es asi podrían decir cuales son por favor. Gracias

**Comment by arpincheira** [comment]
Hola, no conocen de antemano los subgéneros así que deben buscar alguna forma de modelarlo que les permita obtener la información que desean (**hint:** piensen en la cardinalidad de la relación)
