### ISSUE TITLE
Entrega 3 Apartado 2 : Problema con datos entrega anterior vacios

### ISSUE THREAD

**Issue by mati-gonz** [IIC2413/Syllabus-2021-2#359]
Hola soy del grupo 36, lo que pasa es que cuando entro a la base de datos con "\c grupo36e3"  y luego hago "\d" nos dice que no existe ninguna relación. Según el enunciado, deberían salirnos todas las tablas creadas en la entrega 2. No sé a qué se puede deber ese error, y nos está retrasando con el trabajo. Me gustaría si pudieran ayudarme :
![Screenshot_12](https://user-images.githubusercontent.com/69521778/144117316-bd17419f-5820-4e41-9925-36f769bdd0b1.png)
(

**Comment by arpincheira** [comment]
Hola, puede deberse a que trabajaron en la entrega pasada en una base de datos errónea(grupo36 envés de grupo36e2). Podrías corroborar esto?

**Comment by mati-gonz** [comment]
> Hola, puede deberse a que trabajaron en la entrega pasada en una base de datos errónea(grupo36 envés de grupo36e2). Podrías corroborar esto?

Efectivamente eso hicimos, ya que no recuerdo haber visto que se tuviera que trabajar en "grupo36e2". Cómo lo podemos solucionar?

**Comment by arpincheira** [comment]
Ahora deberían poder acceder a todos los datos desde grupo36e3

**Comment by mati-gonz** [comment]
Sí! ahora si funciona, muchas gracias :)
