### ISSUE TITLE
Entrega 1 Impar: dudas sobre las consultas

### ISSUE THREAD

**Issue by Nicolemarin** [IIC2413/Syllabus-2021-2#36]
1. En el enunciado dice lo siguiente: "Como **referencia**, su esquema **debe soportar** las siguientes consultas. Además, **deberá escribir la primera, la segunda y la tercera** en álgebra relacional y en SQL2."
La duda es:  **¿Solo debemos crear las consultas 1, 2 y 3?**  porque nos dicen que **"como referencia"**, el esquema debe **soportar** todas las consultas.. pero solo dicen soportar, no escribir.

2. En la consulta 4: "Muestre todas las peliculas a las que **tiene acceso** el usuario `Ivarov'."
con **"tiene acceso**" se refiere a..
- TODAS las películas que PUEDE ver? o sea las gratis (que son parte del plan), y además las con costo extra? 
- O se refiere solo a las películas que puede ver SIN costo extra?

Gracias!

**Comment by arpincheira** [comment]
Hola, las respuestas son las siguientes:

1._ Debes considerar **todas las preguntas** para construir su esquema(por ejemplo, si en la pregunta 6 de pide algo que tu esquema no posea entonces no estarías cumpliendo con este requisito). Ahora, se van a evaluar que tengan **escritas** en álgebra relacional y SQL (es decir, deben estar en el informe) las primeras 3 consultas. 

2._ Se refiere a todas las películas que puede ver de forma gratuita a partir de los proveedores en los que se encuentra inscrito.
