### ISSUE TITLE
Entrega 1 Impar Apartado 1.1 : Capitulos por temporada

### ISSUE THREAD

**Issue by nicolaspoli** [IIC2413/Syllabus-2021-2#37]
Hola! Mi duda es, para lo de los capitulos por temporada que deben tener su nombre y duracion, deben ser reales? Para un temporada de, por ejemplo, 24 capitulos, debo ingresar 24 entradas en una base de datos por temporada y por serie? o puede inventarme que tiene un par de capitulos por temporada?

**Comment by arpincheira** [comment]
Hola, puedes suponer que las temporadas son de 5 capítulos o que hasta ahora solo tienen X capítulos publicados(hay series en las que sucede esto pero recomiendo que **tengan por lo menos 3 capítulos**). De todas formas te recomiendo poner esto en los supuestos de tu entrega.

Ahora, con respecto a los nombres de estos, puedes centrarte en nombres de capítulos de series reales para no tener que inventar tantos nombres

**Comment by nicolaspoli** [comment]
ok, muchas gracias!
