### ISSUE TITLE
Entrega 1 Par Apartado 2.1: Entidad videojuegos 

### ISSUE THREAD

**Issue by scavagnaro** [IIC2413/Syllabus-2021-2#38]
Hola! ¿Es necesario que en la entidad videojuegos se presenten los atributos géneros y subgéneros, o estos pueden aparecer en una tabla aparte?

**Comment by amparostevens** [comment]
Hola! 😄 
Eso forma parte de la modelación, por lo tanto,  tenerlos en una tabla aparte y luego relacionarlos o tenerlo en la misma tabla depende de ti. Eso si, te recomiendo tomar en cuenta las consultas que deben realizar y elegir la modelación que haga que las consultas sean más simples (para no complicarte de más).

**Comment by scavagnaro** [comment]
Hola! Nuestro problema es que, como pueden haber distintas cantidades de géneros y subgéneros, si es que estos  tienen que salir en las consultas? Porque significaría tener entidades de videojuegos repetidos para acomodar lso géneros y subgéneros.

**Comment by amparostevens** [comment]
Para aclarar, género y subgénero no son atributos de los videojuegos, sino que un videojuego pertenece a una o más categorías de géneros/subgéneros. Dicho esto, el enunciado menciona que _si no se especifica el atributo, debe proyectar la entidad entera_. 
Para complementar, se pueden mostrar todos los géneros separados por coma (al realizar una agregación) y así no tendrías repetidos los juegos.

Espero que se haya entendido!

**Comment by mjsifri** [comment]
Hola, entonces cuando hay que proyectar la entidad completa, no es necesario poner los géneros y subgéneros del videojuego, ya que no serían atributos?

**Comment by arpincheira** [comment]
Eso va a depender de cómo lo modeles, si no lo modelas como atributo entonces no es necesario, de lo contrario si lo va a ser
