### ISSUE TITLE
Entrega 1 Par Apartado 2.1: La calificación es PG13 para todos los videojuegos?

### ISSUE THREAD

**Issue by DQPalomera** [IIC2413/Syllabus-2021-2#39]
Hola!

En la parte de Videojuegos sale:
> Videojuegos. Los videojuegos, tienen al menos: título, puntuación, **clasificación (PG13)**, fecha de lanzamiento.

Lo que se encuentra entre paréntesis quiere decir que la clasificación de todas las películas debe ser **PG13** u otra cosa?

La duda se consolidó ya que si todas son PG13 no se podrían hacer consultas para este tipo de atributo como condicional, aunque igual no hay consultas que lo pidan directamente, igual no sabemos si podría ser una consulta intermedia.

**Comment by arpincheira** [comment]
Ese es un tipo de calificación de películas, puedes ver más información en [este link](https://es.wikipedia.org/wiki/Sistema_de_calificaciones_de_la_Motion_Picture_Association)

**Comment by DQPalomera** [comment]
> Ese es un tipo de calificación de películas, puedes ver más información en [este link](https://es.wikipedia.org/wiki/Sistema_de_calificaciones_de_la_Motion_Picture_Association)

Ahh entiendo, entonces eso solo era un ejemplo, podría ser tanto PG13 como G, PG, R, NC17, etc

Muchas gracias 😄 !! sobre todo por el día

**Comment by DQPalomera** [comment]
Me entró otra duda, dado que la parte de los grupos pares son videojuegos, también debemos ocupar la clasificación de películas (G, PG, PG-13, R, NC-17, del link que me adjuntaste) en vez de la clasificación para videojuegos (EC, E, E10+, T, M, AO)? Que saqué de [aqui](https://www.esrb.org/ratings-guide/) y [acá](https://www.enticconfio.gov.co/conoce-como-se-clasifican-los-videojuegos)

Gracias de antemano!

**Comment by arpincheira** [comment]
Efectivamente pueden poner ese mismo tipo de clasificación aunque no concuerde necesariamente con la realidad(esto es válido por como fue propuesto por el enunciado)
