### ISSUE TITLE
¿Hay una grabación de la ayudantía?

### ISSUE THREAD

**Issue by EugenioCruz** [IIC2413/Syllabus-2021-2#4]
Hola! Quería preguntar si es que se grabó la Ayudantía 1 el día Viernes, y si es así ¿Dónde se encuentra?

Gracias de antemano!

**Comment by conyortizsimpson** [comment]
Hola! Se subirá en el transcurso de la tarde al github, disculpa la demora!

**Comment by conyortizsimpson** [comment]
Aquí podrás encontrar las ayudantías: https://github.com/IIC2413/Syllabus-2021-2/tree/master/Ayudantias

**Comment by Nicolasramos411** [comment]
Hola! Aprovecho de avisar que está prohibido el acceso con el mail UC. Para que puedan corregirlo,

Gracias!

**Comment by conyortizsimpson** [comment]
Hola! Podrías confirmar que aún no te funciona? Acabo de probar con mi correo :)

**Comment by Nicolasramos411** [comment]
Si! Ya funciona.
