### ISSUE TITLE
Entrega 1 Par Apartado 2.1: ¿Los proveedores tienen distintos precios?

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2413/Syllabus-2021-2#40]
Hola, quisiera saber si los proveedores pueden vender a distintos precios los videojuegos. En ese caso tambien deberiamos vincular al proveedor dentro de las preordenes (pues el precio rebajado también sería distinto),

Gracias.

**Comment by arpincheira** [comment]
Hola, diversos proveedores pueden vender el mismo juego a distinto precio y si, efectivamente el precio de preorden puede variar entre los proveedores también
