### ISSUE TITLE
Entrega 1 Par Apartado Proveedores: ¿Un proveedor puede tener más de una plataforma?

### ISSUE THREAD

**Issue by cadaeic314** [IIC2413/Syllabus-2021-2#41]
Me surge la duda de si un proveedor puede tener más de una plataforma, ya que el modelado de esta situación sería distinto al de una sola. En el enunciado solo se especifica que

> Los proveedores tienen nombre y plataforma.

Muchas gracias de antemano.

**Comment by arpincheira** [comment]
No, los proveedores poseen una única plataforma

**Comment by arpincheira** [comment]
Los proveedores poseen una única plataforma la cual es propia de ellos.

**Comment by cadaeic314** [comment]
lo de propia de ellos, se refiere a que no pueden haber dos proveedores con la misma plataforma?

**Comment by arpincheira** [comment]
Hola, perdón por la confusión, con plataforma nos referíamos a "distintos tipos de dispositivos que ejecutan los videojuegos".

**Comment by cadaeic314** [comment]
Ahhh yaya, entonces las plataformas pueden repetirse entre proveedores y cada proveedor puede tener una o más plataformas o no?

**Comment by arpincheira** [comment]
Hola, lo primero si, lo segundo lo recomiendo poner como **supuesto** en la entrega (en la siguiente se va a definir bien), pero a priori tengo entendido que los proveedores son "normalmente" enfocados a una única plataforma.

**Comment by cadaeic314** [comment]
vale, muchas gracias 😸
