### ISSUE TITLE
Entrega 1 Impar General: PSQL: Tablas sin primary keys, y multiples keys

### ISSUE THREAD

**Issue by fernandosmither** [IIC2413/Syllabus-2021-2#43]
Hola!

Quería preguntar primero si a efectos del curso podemos crear tablas sin primary keys, leyendo la documentación ví que psql no lo requiere ya que por detrás ya crea un identificador único.

Lo segundo, si tengo una tabla que tiene multiples keys como vimos en ejemplos anteriores de guías,  cómo puedo crear una tabla así en psql?

Gracias!

**Comment by benjavicente** [comment]
Hola! **Para esta entrega no es necesario que se preocupen de añadir _primary keys_ (PK) correctamente en las tablas**. Solo necesitan que las tablas tengan lo especificado en el esquema y que estas estén pobladas para mostrar los resultados de las 3 primeras consultas.

Como regla general, no es recomendado crear tablas sin PK, ya que las tuplas no tendrán una manera de identificarlas. Sin PK, puede ocurrir que tuplas existan con los mismos valores, por ejemplo, dos tuplas/personas `("Tomás", 20)` y `("Tomás", 20)` son indistinguibles entre sí. Si tuviesen un id (que sería PK), se podrían distinguir (repito, esto no se pide en esta entrega). 

En la [documentación de PostgreSQL](https://www.postgresql.org/docs/8.1/ddl-constraints.html#AEN2038) hay un ejemplo de como añadir multiples PK:

```SQL
CREATE TABLE example (
    a integer,
    b integer,
    c integer,
    PRIMARY KEY (a, c)
);
```
