### ISSUE TITLE
Entrega 1 Impar Apartado 1.1 : Obligatoriedad de Requerimientos

### ISSUE THREAD

**Issue by JJVergara** [IIC2413/Syllabus-2021-2#44]
Hola! Tenía una duda respecto a la obligatoriedad de los requerimientos para la base de datos. Entiendo que hay ciertos atributos de los objetos que son obligatorios de poner en la base de datos, pero mi duda es si se pueden juntar bases de datos, o también es obligatorio hacerlos de forma separada. Por ejemplo: En vez de hacer una base de datos de Películas y otra de Series, puedo hacer una sola que sea de Películas y Series?

**Comment by arpincheira** [comment]
Hola, no me queda del todo claro a lo que te refieres con bases de datos para cada cosa. En el caso de que te refieras a tablas entonces te recomiendo fuertemente realizar la subdivisión entre películas y series pues ambas tienen ciertas características las cuales son diferentes. Si te referías a bases de datos como tal, la idea es que estén en la misma base de datos (pues se les entrega una única base de datos para realizar esta entrega).
