### ISSUE TITLE
Entrega 1 Impar Apartado Final : Debemos crear instancias para las consultas 4,5,6?

### ISSUE THREAD

**Issue by fernandosmither** [IIC2413/Syllabus-2021-2#45]
Debemos crear instancias para las consultas 4,5,6?

**Comment by arpincheira** [comment]
Hola, solo es necesario que creen instancias completas para las primeras 3 consultas, el resto solo las debes considerar al momento de crear el esquema(puede darse de que hayan ciertos datos que no sean requeridos para estas pero si para el resto). Ahora, deben crear todas las tablas de su esquema en su base de datos(aunque algunas tablas no las poblen con datos).
