### ISSUE TITLE
Entrega 1 Impar Apartado 1.2 : Año en registro de contenido visto

### ISSUE THREAD

**Issue by fernandosmither** [IIC2413/Syllabus-2021-2#46]
Hola!

Con mi grupo teníamos una duda de enunciado, ya que según lo que se pide:
![image](https://user-images.githubusercontent.com/66154723/133022238-306d763e-b535-49d6-90a2-df0282f69136.png)

Interpretamos que este sería un registro "binario" donde hay entradas **ssi** vio un contenido, sin embargo la consulta número 5 parecería indicar que también se debe registrar un año de visualización, pero esto no está incluido en el enunciado.

Saludos!

**Comment by fernandosmither** [comment]
PD: Sabemos que la consulta 5 no se evaluará ahora

**Comment by arpincheira** [comment]
Hola, con respecto a la primera pregunta, te recomiendo ver la issue #36.

Con respecto a la segunda, no, no puede acceder a una película a la que básicamente no tiene acceso(pues si no está subscrito a algún proveedor que la tenga entonces no puede verla). Con respecto a la segunda parte de esta pregunta, te recomiendo ver la issue #23.
