### ISSUE TITLE
Entrega 1 Par Apartado 2.1: Registro histórico de las subscripciones.

### ISSUE THREAD

**Issue by jcastaran** [IIC2413/Syllabus-2021-2#47]
Hola, en el apartado 2.1 en la seccion "Usuarios" mencionan lo siguiente:
>  La plataforma tambien mantiene un registro de las horas de juego de los usuarios en cada juego y un registro historico de las subscripciones y su estado (activa, inactiva).

A que se refiere con registro historico? Debemos por ejemplo almacenar en que fechas el usuario estuvo suscrito a "Starcraft" o solo indicar que suscripciones estan actualmente activas?

**Comment by hebusch** [comment]
Hola @jcastaran,
Aquel fragmento del enunciado menciona dos registros que deben llevar los usuarios:

* Registro de horas de juego: debes guardar cuantas horas el usuario ha jugado a cada juego.
* Registro histórico de subscripciones: debes llevar registro de todas las suscripciones que el usuario tiene o ha tenido e indicar si está activa o inactiva.
