### ISSUE TITLE
Entrega 1 Impar Apartado 1.1 : [Estado de suscripción]

### ISSUE THREAD

**Issue by PaulaGrune** [IIC2413/Syllabus-2021-2#48]
> Hola! Para la parte de usuarios sale "Adicionalmente existe un registro histórico de las subscripciones de cada usuario y su estado (activa, inactiva)". ¿Es necesario que esté explícitamente en una tabla la información activo/inactivo o basta con tener las fechas en las que está activo?
De antemano muchas gracias :)

**Comment by arpincheira** [comment]
Hola, te recomiendo ver la issue #47. De todas formas te voy a dar el siguiente ejemplo:

Yo me subscribí el 2010 a WoW y pagué esa subscripción hasta principios de este año. Actualmente la subscripción se encuentra inactiva y por ende en el registro debe aparecer que esa subscripción estuvo activa durante ese tiempo pero que ahora se encuentra inactiva. 

De todas formas, en esta entrega depende de como quieran modelarlo y los supuestos que tomen al respecto siempre y cuando sean capaces de contestar todas las preguntas que se encuentran planteadas en el enunciado

**Comment by PaulaGrune** [comment]
Perfecto! Muchas gracias!! :)
