### ISSUE TITLE
Duda escritura JOIN

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2413/Syllabus-2021-2#49]
Hola! Tenía una duda práctica. Sucede que en clases vimos que cuando queremos hacer un JOIN entre dos tablas que tienen el mismo nombre de un atributo se tiene que especificar a qué tabla pertenece el atributo, por ejemplo, películas.id vs usuarios.id. Mi duda es la siguiente, cuando escribo el siguiente código, inventado, en SQL:

SELECT *
INTO nueva_tabla
FROM películas, usuarios
WHERE películas.id = usuarios.id

me arroja un error ya que al crear la nueva tabla filtrada estaría incluyendo dos columnas con el mismo nombre, en este caso id, es por ello que quería preguntar cómo solucionar este problema.
Otro ejemplo sería el ejercicio visto en la ayudantía previa al control, donde se hacía un self join. En ese caso se formaba una gran tabla con atributos de igual nombre pero se diferenciaban según la tabla de origen, por ejemplo, películas.id vs usuarios.id sin embargo, lo anterior llevado a SQL me arrojaría este mismo error. 
Creo que una opción sería alterar los nombres de los atributos pero no creo que sea la opción más eficiente.

Espero se entienda mi duda.
Gracias!

**Comment by amparostevens** [comment]
Hola!
Me pregunto si es necesario que crees una nueva tabla, ya que si es sólo para hacer consultas no lo veo necesario. 

En caso de que lo necesites, podrías hacer algo como `SELECT peliculas.*, usuario.nombre`, de esta forma seleccionas todo de una tabla pero no de la otra. 

También, si es que quieres conservar todas las columnas, puedes darle un alias a, por ejemplo, user.id de la forma `SELECT user.id AS idUsuario` y así no tendrías el alcance de nombres.

**Comment by fernandolalanne** [comment]
Gracias! Ahi me quedo mas claro sin embargo, me quedó una duda.
En primer lugar me estaba poniendo en el caso de que quiera crear una tabla filtrada a partir de otra equivalente al usar el “rho” en álgebra relacional. En segundo lugar, si yo quisiera hacer lo anterior pero tengo una tabla con 10 atributos y le hago el join con otra tabla que 10 atributos y tienen atributos con nombres iguales. Lo que eventualmente deberia tener seria una tabla con 20 atributos donde alguno de ellos tienen igual nombre entonces, si quiero que se me muestre la tabla completa para evitar confusiones de nombre tengo que aplicar el comando que tu me diste 20 veces? O puedo seleccionar todas las colnas y cambiar solo algunas de nombre?.


Gracias!

**Comment by amparostevens** [comment]
En ese caso deberías especificar cada columna y ocupar AS en los que desees cambiar el nombre. Otra opción sería cambiar el nombre de las columnas en las tablas originales y evitar que se llamen iguales entre tablas (por ejemplo, userId y movieId en vez de simplemente id).

Igualmente vuelvo a insistir en porqué deseas crear una nueva tabla con la información, que va a quedar de forma permanente en tu base de datos (a menos que la borres), si es que vas a utilizar esa información para realizar una consulta, por poner un ejemplo: mostrar todos los usuarios con menos de 20 películas. 

Te recomiendo que hagas **consultas anidadas**, de esta forma no creas nuevas tablas y no deberías tener problemas por alcance de nombres, ya que al hacer un join las columnas quedan como nombreTabla.columna
