### ISSUE TITLE
Entrega 1 Par Apartado 1: Poblando tablas

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2413/Syllabus-2021-2#50]
Quería consultar sobre como poder importar datos de un archivo creado en mi PC y cargarlos sobre las tablas del servidos. Lo estoy haciendo con **\COPY** pero me ocurre el error :
_4lon5\Desktop\UC\IIC2413\Database\Ejemplo_E1\Providers.csv: No such file or directory_
Probé usando rutas relativas y absolutas pero no logro dar con la solución :/

**Comment by hebusch** [comment]
Hola @AlonsoZamorano!

Para poblar las tablas **del servidor**, es necesario que tu archivo *.csv* esté subido **en el servidor**. 

Una vez el archivo esté en el servidor puedes usar la ruta relativa de este para poblar las tablas. 

Saludos.

**Comment by AlonsoZamorano** [comment]
Perfecto! Muchisimas gracias
