### ISSUE TITLE
Entrega 1 Impar Apartado 1 : Duda con el arriendo de la spelículas

### ISSUE THREAD

**Issue by BenjaRubio** [IIC2413/Syllabus-2021-2#51]
Hola! cuando dice "las películas pagadas se rigen bajo un esquema de arriendo, es decir, están disponibles para ser vistas por el
usuario por un tiempo limitado". Este tiempo limitado es igual para todas las películas, o depende de ellas?

**Comment by hebusch** [comment]
Hola @BenjaRubio, tu duda fue contestada en la issue #28, saludos
