### ISSUE TITLE
Entrega 1 Par Apartado Consulta 3: [Duda con subgeneros]

### ISSUE THREAD

**Issue by gore26** [IIC2413/Syllabus-2021-2#52]
Hola, cuando nos mencionan que debemos mostrar los nombres de los juegos del género "FPS" o alguna de sus subgéneros, por ejemplo, si "FPS" tiene al subgénero "guerra", pero el subgénero "guerra" también pertenece al género "estrategia", en este caso debiésemos también nombrar al juego que tiene como género "estrategia" y subgénero "guerra"? ya que "guerra" sería subgénero de "FPS".
Gracias!

**Comment by arpincheira** [comment]
Hola, normalmente depende del videojuego, un ejemplo podría ser el juego el residente evil 7 o el bioshock los cuales pertenecen a los géneros de FPS(_first person shooter_), estrategia y terror sin ser necesariamente pertenecientes al subgénero de guerra. 

Ahora, considerando tu ejemplo, si pide que pertenezcan a un subgénero de FPS entonces debes considerar que existe una posible forma de obtener los subgéneros de FPS y de ahí obtener a los juegos que los posean. (pese a que no necesariamente pertenezcan al género dichos juegos FPS por lo menos en esta entrega)

**Comment by gore26** [comment]
Ahhh, perfecto, muchas gracias!
