### ISSUE TITLE
Entrega 1 Par Apartado 2.1: Cuenta y género

### ISSUE THREAD

**Issue by mjsifri** [IIC2413/Syllabus-2021-2#53]
Hola! Los usuarios deben pagar por crearse una cuenta en algún proveedor? o solo se paga por las suscripciones a los juegos que ofrecen los proveedores donde los usuarios tienen cuenta? (donde no se pagó por tener esa cuenta)
Y con respecto a los géneros de los videojuegos, no entiendo a que se refiere con que un juego puede tener uno o más géneros y subgéneros. Sería correcto decir que el juego tiene un género, donde este puede ser un género en sí, o subgénero de otro género, pero el atributo guardaría solamente un "tipo" de juego. Por ejemplo, el género amor tiene subgéneros comedia romántica y drama. Podría un juego tener como atributo género comedia romántica? (Además, existiría otra tabla donde los géneros tienen asociados sus subgéneros). O cada juego tiene que tener un género y además un subgénero?
Ojalá se entienda :)

**Comment by arpincheira** [comment]
Hola, si bien en la vida real pueden darse casos en los que se debe pagar para poder acceder a un proveedor, esto no se encuentra explícito en el enunciado por lo que por esta entrega pueden considerar que los proveedores son mediadores de transacciones solamente. 

Con respecto a lo segundo, todo juego debe tener por lo menos un género y subgénero.
