### ISSUE TITLE
Duda sobre buenas practicas

### ISSUE THREAD

**Issue by v4rgas** [IIC2413/Syllabus-2021-2#54]
Si tuviera que guardar en una base de datos computadores + sus sistemas operativos, deberia guardar el sistema operativo como una columna de la tabla de computadores o crear una tabla con los sitemas operativos y poner el ID en la tabla de los computadores?

Ejemplo:
```
computadores(id, marca, precio, id_sistema_operativo)
sistemas_operativos(id, nombre)
```

vs
```
computadores(id, marca, precio, nombre_sistema_operativo)
```
O si fuese una relacion de muchas a muchas (como si los computadores tuvieran mas de un SO)
```
computadores(id, marca, precio)
computadores_so(id_computadores, id_sistema_operativo)
sistemas_operativos(id, nombre)
```
vs
```
computadores(id, marca, precio, nombre_sistema)
computadores_so(id_computadores, nombre_sistema_operativo)
```
Muchas gracias!

**Comment by EstebanReyes1998** [comment]
Hola @v4rgas !

Respecto a tu pregunta, aunque siempre va a depender del contexto de tu problema, siempre es una buena práctica modularizar, o sea, subdividir en partes más pequeñas, tu modelación.

Digamos, por ejemplo, que utilizas esta tabla para tu base de datos:

computadores(id, marca, precio, nombre_sistema_operativo)

Y por alguna razón, te diste cuenta que al insertar los datos en tu tabla escribiste mal el nombre de un sistema operativo, en vez de escribir "Windows" escribiste "Wuindous" en todas las filas del programa.

Para solucionar esto, deberías recorrer nuevamente todas las filas de tu tabla y cambiar en cada una el valor de la columna nombre_sistema_operativo. ¿Suena tedioso no? Especialmente cuando trabajas con una gran cantidad de datos.

Sin embargo, si hubieras utilizado:

computadores(id, marca, precio, id_sistema_operativo)
sistemas_operativos(id, nombre)

Bastaría apenas que corrijas en la tabla sistemas_operativos(id, nombre) el nombre que estaba malo. Como las tablas se relacionan por el id, el cambio se reflejará automáticamente en todas las tablas, y será mucho más fácil.

En la relación de muchos a muchos ocurre básicamente lo mismo.

**Comment by v4rgas** [comment]
Esto me lo deja mucho mas claro! gracias
