### ISSUE TITLE
Entrega 1 Par Apartado X: [Atributos videojuegos]

### ISSUE THREAD

**Issue by mjsifri** [IIC2413/Syllabus-2021-2#56]
Hola! Quería saber si hay alguna forma de guardar más de un valor dentro de un atributo, por ejemplo, si un videojuego tiene más de un género, estos se podrían guardar en el mismo atributo o tendría que repetir la tupla y poner en cada una un género distinto?

**Comment by arpincheira** [comment]
Hola, te recomiendo fuertemente revisar el esquema que se les entregó para el control 1  y la relación que existe entre los convencionales y las sesiones

**Comment by vichoruiz** [comment]
hola, estoy viendo lo mismo, pero en otra issue ponen que el videojuego debe tener un genero y subgenero como atributo. pero podría tenerlo en otra tabla relación?

**Comment by arpincheira** [comment]
Depende principalmente de cómo lo quieras modelar, mi comentario es más bien una recomendación pero no es necesariamente "mandatorio".
