### ISSUE TITLE
Entrega 1 Par Apartado X: [Duda enunciado consulta 3]

### ISSUE THREAD

**Issue by mjsifri** [IIC2413/Syllabus-2021-2#57]
Hola! No me queda claro el enunciado de la consulta 3. Se refiere a que:
1. Los juegos que tengan como género FPS, o que alguno de sus subgéneros sea FPS
2. Los juegos que tengan como género FPS o que tengan como género alguno de los subgéneros de FPS
Saludos

**Comment by arpincheira** [comment]
Hola, se refiere a que su género sea FPS o que su subgénero sea un subgénero de FPS. Aunque dada la redacción de la pregunta la 2a interpretación que propones también se podría considerar como correcta
