### ISSUE TITLE
Entrega 1 Impar Apartado X : [algebra relacional similar al consulta SQL]

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2413/Syllabus-2021-2#58]
Hola!

Me surgió la duda de si es necesario que el algebra relacional sea similar a la consulta SQL. Esto por que al hacer las consultas en SQL se pueden usar comandos de SQL avanzado que no se pueden hacer directamente en algebra relacional y hacen a la consulta mas simple.

Gracias :)

**Comment by benjavicente** [comment]
Hola! No es necesario, pueden utilizar SQL más avanzado para las consultas. Con que estas funcionen va a estar bien.
