### ISSUE TITLE
Entrega 1 Impar Apartado 1.2.6. : Duda sobre algebra relacional para esta consulta

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#60]
Hola, esperando que se encuentren bien, quería preguntar si es posible escribir en álgebra relacional la consulta 6. Estoy tratando pero me complica la parte de sumar el dinero gastado en cada película vista en un plan que no lo cubre. Desde ya gracias y feliz 18!

**Comment by benjavicente** [comment]
Hola! El enunciado especifica que deben escribir **la primera, la segunda y la tercera** consulta en álgebra relacional y SQL!

El resto es para que se hagan una idea de como tiene que estar estructurada la base de datos. En la 6 van a necesitar operaciones que no existen en álgebra relacional. Feliz 18! 🎶  🇨🇱

**Comment by JuanpaBC** [comment]
gracias!
