### ISSUE TITLE
Entrega 1 Par Apartado 2.2: ¿A qué se refieren con el titulo de las reseñas?

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2413/Syllabus-2021-2#61]
En un principio había pensado que el titulo de las reseñas hacía referencia a un nombre para la reseña, pero pense que podía referirse al titulo del juego que hablan. ¿A cual de estos se refiere este atributo?

**Comment by arpincheira** [comment]
Título/Nombre de la reseña

**Comment by AlonsoZamorano** [comment]
Perfecto! Muchas gracuias
