### ISSUE TITLE
Entrega 1 Par: Son necesarias las llaves siempre?

### ISSUE THREAD

**Issue by sebamoreno2811** [IIC2413/Syllabus-2021-2#63]
Tenemos la duda de si es necesario que todas las tablas tengan llaves, ya que no les encontramos sentido en algunas y creemos que es mejor que no tengan por ejemplo llaves primarias.

**Comment by benjavicente** [comment]
Hola, algo similar fue respondido [en esta issue](https://github.com/IIC2413/Syllabus-2021-2/issues/43#issuecomment-918353974), que en resumen es que no es necesario, **pero generalmente deberían**, porque las tuplas deberían poder ser identificables para poder ser distinguidas unas de otras.
