### ISSUE TITLE
Duda materia sobre relaciones múltiples en diagrama E/R

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#66]
Hola, espero que estén bien. Leyendo las slides de diagramas E/R no logré entender cómo funcionan y en qué casos se dan las relaciones múltiples. Adjunto foto de la parte que no entiendo a continuación:
![image](https://user-images.githubusercontent.com/80859173/134785676-166e1c3c-5336-4ba4-bcaa-ffcd41af6e5a.png)

Agradezco cualquier orientación al respecto.

**Comment by arpincheira** [comment]
Hola, la situación que se describe en la imagen se puede transcribir de la siguiente forma:

Existe un proceso correspondiente a alquilar una película, a este proceso le interesa saber tanto la persona que la alquila(cliente), como la película que es alquilada, el local de videos donde se realiza esto y el cajero quien registra la transacción.  Esta te permitiría responder quien ha alquilado esa película, en que local se alquiló dicha película, que película fue alquilada y quien registró el alquiler de la película. 

Por lo general estos casos se dan cuando existen múltiples agentes(quienes fueron modelados como entidades) los cuales realizan una determinada acción o poseen una cierta interacción en donde sea importante almacenar o acceder a esa información.

**Comment by JuanpaBC** [comment]
gracias, me queda más claro ahora. Solo para confirmar, si en vez de la entidad persona existieran las identidades Cliente y Cajero, esa relación múltiple ya no sería necesaria y el diagrama pasaría a ser como una X? adjunto una foto de lo que planteo:

![image](https://user-images.githubusercontent.com/80859173/134788124-bc247744-df16-4060-a9cb-8cb9d93a9a7a.png)

**Comment by arpincheira** [comment]
Em... se podría decir que si, aunque en esos casos deberías verificar que efectivamente los atributos de cajero y cliente varíen considerablemente entre si, porque de lo contrario tendrías dos entidades con exactamente los mismos dos atributos o podría ser un indicativo de que existe una entidad que podría abarcar los atributos comunes de ambas(teniendo solo algunos atributos diferentes y ser necesaria esa relación múltiple pero a partir de una herencia).

**Comment by JuanpaBC** [comment]
ya perfecto, muchas gracias!
