### ISSUE TITLE
Entrega 2 Impar Apartado 2.1: sobre modelo E/R

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#67]
Hola, en el enunciado aparece "_Construir un modelo de Entidad/Relación que represente de manera fiel la situación
planteada en la entrega 1_". Tengo la duda de si el diagrama E/R que debemos hacer debe ser estrictamente en base al esquema entregado en la entrega 1, o si podemos hacerlo en base a versiones mejoradas y actualizadas de nuestro esquema. 

Desde ya gracias.

**Comment by arpincheira** [comment]
Hola, efectivamente la idea es que lo hagan a partir de versiones mejoradas y actualizadas de su esquema. Además yo les recomiendo pensar en posibles mejoras y esperar a los datos para poder realizar el diagrama y esquema final, pues estos pueden traerles una que otra ayuda. Otra cosa en la que pueden avanzar es en la base de su página en php para que cuando tengan los datos procesados, sea mucho más ameno el proceso.

**Comment by JuanpaBC** [comment]
vale muchas gracias!
