### ISSUE TITLE
Entrega 2 Par Apartado 2: ¿Videojuegos tienen un serial?

### ISSUE THREAD

**Issue by pablosbw** [IIC2413/Syllabus-2021-2#68]
Hola! Espero que se encuentren bien.
Con mi compañera estábamos discutiendo al respecto de algunos aspectos de la cardinalidad entre la relación de juegos y personas y llegamos a un punto sobre una característica de los juegos para determinar esto. ¿Se debe considerar que un juego tiene un serial único para cada persona? Por ejemplo si yo compro minecraft asumo que viene con un serial "1234", y si una segunda persona lo compra viene con otro serial "1235" y ¿eso hace que sean juegos distintos?

Saludos y muchas gracias!

**Comment by benjavicente** [comment]
No puedes considerarlo como cierto hasta que se entreguen los datos a utilizar de la entrega.

Me imagino que en el caso que planteas va a existir dos tuplas en la tabla de videojuegos, una con `serial=1234` y otra con `serial=1235`. En ese caso, los juegos serían distintos (por serial), pero ambos representarían un juego con `nombre=minecraft`, con todos los atributos que le corresponden. **Esto es una anomalía, porque todos esos atributos se estarían almacenando múltiples veces**. ¿Qué pasa, si por ejemplo, se quiere agregar un juego nuevo, que no ha sido comprado aún? ¿Cómo puedes ver que ese juego existe?. 

Te recomiendo ver la parte de anomalías y descomposición de la clase 6, donde se menciona como abordar esos casos.
