### ISSUE TITLE
Duda materia Agregación

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#69]
Hola, viendo las diapos me costó entender cuál fue la gracia, la finalidad o la justificación de ocupar agregación. Tanto para el ejemplo puntual de la diapo como en general todavía no entiendo cuándo conviene encapsular relaciones y qué beneficio se obtiene. Adjunto foto de la diapo por si acaso:
![image](https://user-images.githubusercontent.com/80859173/134980276-5483687a-2b4b-4afd-8412-2a6faa3e01ac.png)

Desde ya muchas gracias.

**Comment by matiastoro** [comment]
La agregación se ocupa cuando quieres relacionar entidades con otras relaciones. Esto no se puede sin agregación ya que las relaciones solo relacionan entidades con otras entidades.
Entonces se crea una "entidad virtual" que encapsula la relación y las entidades que conecta.
En el ejemplo, es necesaria una entidad virtual, de lo contrario podrias relacionar una persona con un local de video y una pelicula, de peliculas que no estan en ese local de videos. Por ejemplo podrias guardar que Juan arrendo 'Up' en 'Blockbuster', pero 'Up' no esta en 'Blockbuster', es decir, la tupla ( 'Up', 'Blockbuster') no se encuentra en la relación "tiene". Al usar entidades virtuales, relacionamos Persona con la relacion misma, evitando la anomalía descrita anteriormente.
Espero que te haya aclarado mas el tema.

**Comment by JuanpaBC** [comment]
Vale muchísimas gracias profe me quedo clarísimo!
