### ISSUE TITLE
Cómo obtener las carpetas de la ayudantía para la E2

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2413/Syllabus-2021-2#72]
> Ingresa los detalles de tu pregunta aquí, o da cualquier información adicional al título que ayude al equipo docente a responder tu pregunta
Hola! Ustedes en la ayudantía para la E2 utilizaron archivos dentro de la carpeta sites. Mi duda es si esas carpetas se deben crear o están pre hechas en alguna parte.

Desde ya muchas gracias!

**Comment by arpincheira** [comment]
Hola, la carpeta Sites deberían tenerla en todos los grupos pues fue creada en conjunto a los respectivos usuarios. Ahora, el contenido de esta carpeta correspondiente a la página web lo deben crear ustedes pues es parte de la entrega(aunque pueden basarse en los archivos de la ayudantía)
