### ISSUE TITLE
Servidor  duda con ingresar desde navegador

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2413/Syllabus-2021-2#73]
Hola!, una vez que empecemos a crear los archivos php y html, como ingresamos desde el navegador para ver como se esta viendo la pagina?

**Comment by arpincheira** [comment]
Hola, van a poder ver El Progreso ingresando a http://codd.ing.puc.cl/~grupoX/index.php donde X corresponde a tu número de grupo
