### ISSUE TITLE
Guía 4: No entiendo cómo funciona 3NF y BCNF

### ISSUE THREAD

**Issue by En-clases** [IIC2413/Syllabus-2021-2#74]
Hola! Aún no logro entender bien cuándo una tabla esta en 3NF y en BCNF.

No hay 3NF cuando ocurre que un conjunto de atributos de una tabla definen otro conjunto de atributos que a su vez definen otro conjunto de la misma tabla?
No hay BCNF cuando existen atributos de una tabla que no son ```Primary Key``` y que definen otro atributo de la misma tabla? Y si es así, no entiendo el contraejemplo que dan en la solución de la pregunta P2-b): 
![image](https://user-images.githubusercontent.com/69520590/135360256-640bad49-7a0b-45dc-b577-974de8a0c622.png)
ya que se supone que actor sí es una ```Primary Key```.

Desde ya, gracias.

**Comment by En-clases** [comment]
😢

**Comment by matiastoro** [comment]
FNBC:  para toda df X->Y, el lado izquierdo X es superllave
3FN: para toda df X->Y, (el lado izquierdo X es superllave) OR  (el lado derecho Y pertenece a una llave)

La llave minimal de cine es (nombre, anho, actor, personaje).
DF1 es contraejemplo para 3FN porque: (1) (actor) no es superllave, y (2) genero no pertenece a una llave.
DF1 tambien es contrajemeplo para FNBC porque (actor) no es superllave.

**Comment by En-clases** [comment]
me quedó muy claro, gracias!
