### ISSUE TITLE
Entrega 2 Impar Apartado PHP : Qué extensiones ocupar de php para VS Code

### ISSUE THREAD

**Issue by En-clases** [IIC2413/Syllabus-2021-2#75]
Hola! Cuáles son las extensiones de VS Code para programar en php utilizados en la ayudantía de entrega 2? Me pasa que VS Code no reconoce algunos comandos de php :c. Por ejemplo, no reconoce el tag <?php?>.
Desde ya, gracias.

**Comment by conyortizsimpson** [comment]
Hola! Utilicé la extensión **Emmet Keybindings** que solamente sirve para tags html ([aquí](https://code.visualstudio.com/docs/editor/emmet) puedes ver más detalles de esta extensión). Tiene maneras de programar atajos nuevos pero por defecto solo acepta tags html (h1, p, div, entre otros).
Existen otras extensiones que pueden ayudarte con php, pero en la ayudantía no usamos ninguna 😄 
Espero que haya respondido tu pregunta!

**Comment by En-clases** [comment]
ahh pensé que usaron más extensions 😅, gracias!
