### ISSUE TITLE
Entrega 2 Par Apartado 2.5 Pagina Web: Uso codigo ayudantia

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2413/Syllabus-2021-2#76]
Hay algún problema con ocupar código de la ayudantía en el diseño de nuestra pagina?, o el código de diseño tiene que ser escrito 100% por nosotros.

**Comment by conyortizsimpson** [comment]
No hay problema, pero si el diseño es igual al de la ayudantía no te dará un bonus 😄
