### ISSUE TITLE
Entrega 2 Par Apartado 2.3: Procesar datos con Python

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2413/Syllabus-2021-2#77]
Hola, de que forma se pueden trabajar los datos con python. Y es equivalente a trabarjarlos con excel?

**Comment by benjavicente** [comment]
Hola! Pueden desde hacer su propio código de lectura y limpieza de datos con por ejemplo con funciones `open`, `str.split`, `file.readlines` o **utilizar librerías externas como [`pandas`](https://pandas.pydata.org/)** (que es lo que recomendamos).

Realizar el mismo en trabajo en herramientas como Excel puede ser más complejo, porque requiere utilizar funciones avanzadas o hacer cambios a mano.

**Comment by raibd** [comment]
Hola, tengo una duda con el procesamiento pero no quiero hacer otro issue. Con respecto a los valores nulos, hay que asignarles el string "null" o se deja vacio?, de todos modos no entiendo tan bien que tipo de limpieza se requiere hacer. 
Gracias

**Comment by arpincheira** [comment]
Hola, en primer lugar, **la mayoría** de las tablas que fueron entregadas **no se encuentran normalizadas**, por lo que no recomendamos en ningún momento que rellenen los valores nulos y creen un conjunto de tablas con la misma distribución de los datos entregados(eso serían 0 puntos en la normalización probablemente). 

Ahora, la idea de los valores nulos en los datos entregados es que se **den cuenta** de que ahí probablemente hay problemas de moderación que ustedes **deben** tratar para poder construir un modelo que se encuentre normalizado. Es por esto mismo que la idea finalmente es que ustedes no "limpien" los datos como tal sino que construyan nuevos archivos `.csv` que posean únicamente la información correspondiente a las tablas que ustedes quieren crear y puedan poblar así su esquema(ideal 1 csv por tabla).

Por último quiero recalcar que **muy** probablemente la existencia de una gran cantidad de datos nulos al interior de una tabla indica que dicha tabla se puede subdividir en un conjunto de tablas más pequeñas. Además recomendamos que utilicen los ejemplos de asignación de id que se encuentran en los datos entregados para poder referenciar los datos entre tablas y poder hacer los joins
