### ISSUE TITLE
Entrega 2 Par: Reación género y video juegos

### ISSUE THREAD

**Issue by matildeotte** [IIC2413/Syllabus-2021-2#78]
Hola! Cómo puedo saber a qué género y sub género pertenece cada video juego? En la base de datos de video juegos no hay ningún atributo que se llame género es decir, nunca se vinclula el género. Además en la base de datos de género sólo se hace la relación entre el género y sus sub géneros. 

También quería saber qué significa el subs_id en la base de datos de pagos. 

Gracias! :)

**Comment by arpincheira** [comment]
Hola, muchas gracias por notar el error, acabo de modificar los datos creando dos nuevos archivos, `videojuego_v2.csv`, el cual posee la información completa de videojuegos y sin columnas faltantes,  y `videojuego_genero.csv` que posee la información respectiva para que puedan acceder a los géneros de los videojuegos en el caso de que hayan descargado el archivo anterior.

Con respecto a subs_id, este hace referencia al id correspondiente a la subscripción de un usuario, indicando la subscripción a la que corresponde dicho pago.

**tip:** puede que videojuego - genero actualmente se pueda modelar de la forma videojuego-genero/subgenero, lo que explicaría el motivo por el cual poseen columna género y no subgénero

**Comment by matildeotte** [comment]
gracias!
