### ISSUE TITLE
Duda materia Dependencias: sobre dependencia trivial

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2413/Syllabus-2021-2#79]
Hola, si bien me hace sentido lo que dice la observación de la sgte diapo:
![image](https://user-images.githubusercontent.com/80859173/135847296-d0d1537a-7850-46a6-8cc5-dbda4cec9125.png)

me cuesta imaginarme un ejemplo de dependencia trivial en una relación, quizás no le he entendido muy bien, por si me pueden ayudar. Desde ya gracias.

**Comment by benjavicente** [comment]
Hola!

Digamos que tenemos una tienda con atributos `(nombre="Blockbuster", tipo="videoclub", fundacion=1985, activa=Falso)`, es decir, que `X = {nombre, tipo, fundacion, activa}`. En la dependencia trivial `X → Y`, `Y` es un subconjunto de `X`, todo elemento de `Y` está en `X` (es decir, Y es una parte de X).

Entonces considerando, por ejemplo, `Y = {tipo, activa}`, **es trivial obtener el tipo y si una tienda está activa**, sabiendo de antemano que la tienda tiene nombre Blockbuster, **es de tipo videoclub**, fue fundada en 1985 y **no está activa**.

**Comment by JuanpaBC** [comment]
vale me queda más claro, muchas gracias!
