### ISSUE TITLE
Uso de CREATE

### ISSUE THREAD

**Issue by ferrazuriz** [IIC2413/Syllabus-2021-2#8]
Hola,
¿Se pueden crear nuevas tablas con atributos especificos de otras tablas utilizando el formato:
CREATE TABLE new_table_name AS
    SELECT column1, column2,...
    FROM existing_table_name
    WHERE ....;
?
Sería el equivalente a usar rho en algebra relacional.

**Comment by conyortizsimpson** [comment]
Hola! No hay problema que utilices rho en el control, mientras solo utilices cosas de álgebra relacional :) (y no SQL).

**Comment by ferrazuriz** [comment]
Estaba pensando en la parte 2 donde se debe escribir una consulta en SQL

**Comment by conyortizsimpson** [comment]
Ahora entendí bien la pregunta jaja discúlpame. Te recomiendo no utilizar el CREATE TABLE y tratar de investigar acerca del uso de AS y consultas anidadas.
