### ISSUE TITLE
Entrega 2 Par: Información a mostrar en la página web sobre las consultas

### ISSUE THREAD

**Issue by matildeotte** [IIC2413/Syllabus-2021-2#80]
Hola!

Cuando dice que debemos mostrar un juego que cumpla cierta condición, basta con mostrar el nombre del juego o debemos mostrar todos los atributos del juego?

Además quería saber si la consulta 4 y 5 también deben tener matching parcial, es decir que si ingreso el usuario ximelez19 en vez de ximelez1965 igual debe reconocerlo o debe estar escrito exactamente igual?

Gracias!

**Comment by arpincheira** [comment]
Hola, con respecto a la primera consulta, en el caso de que no se especifique deben mostrarr **todos** los atributos correspondientes a dicha entidad. De todas formas se puede realizar una excepción con respecto al género de este pues puede poseer más de uno.

Con respecto a la segunda pregunta, si deben tener matching parcial(se va a evaluar que lo tenga).
