### ISSUE TITLE
Entrega 2 Par Apartado 7

### ISSUE THREAD

**Issue by victoriatsimoyannis** [IIC2413/Syllabus-2021-2#81]
> Ingresa los detalles de tu pregunta aquí, o da cualquier información  adicional al título que ayude al equipo docente a responder tu pregunta

Hola, tengo una pregunta sobre la consulta 7 que piden "Muestre el gasto total de cada usuario por subscripción". Con gasto total se refiere a multiplicar la mensualidad por la cantidad de meses que el usuario se subscribió o solo sumar la cantidad de mensualidad que aparece en la tabla? Si es la opción 1, cómo podríamos acceder a la información de cuantos meses se subscribió ya que las subscripciones que siguen activas no tienen fecha de termino y hay algunas que duran menos de 1 mes.

Gracias.

**Comment by arpincheira** [comment]
Hola, si bien no te puedo dar la respuesta como tal a tu pregunta te puedo decir que los pagos registrados de los usuarios están relacionados de cierta forma con las subscripciones y, como les piden mostrar el gasto de dichos usuarios, **muy probablemente** eso les puede indicar el gasto de dichos usuarios.
