### ISSUE TITLE
Guía 4: No entiendo bien cómo se define BCNF y 3NF

### ISSUE THREAD

**Issue by En-clases** [IIC2413/Syllabus-2021-2#82]
Hola, publiqué una issue hace casi una semana https://github.com/IIC2413/Syllabus-2021-2/issues/74#issue-1011522167 pero no la han respondido. He visto que han contestado issues que se publicaron después de la mía por lo que quizás no lo vieron y por eso lo comento de nuevo por acá. 
Espero puedan ayudarme, gracias.

**Comment by matiastoro** [comment]
respondida
