### ISSUE TITLE
Entrega 2 Par Apartado 2.4

### ISSUE THREAD

**Issue by MotxiGer** [IIC2413/Syllabus-2021-2#83]
En esta pregunta la frase "o que pertenezcan a alguno de sus subgeneros inmediatos" se refiere a

**El videojuego debe tener como genero a un subgenero de nuestro input**, o se refiere a **que nuestro videojuego tiene que tener 
como subgenero a un subgenero de nuestro input?**

**Comment by arpincheira** [comment]
Hola, se refiere a que el videojuego debe tener como género alguno de los subgéneros de su input. 

P.D.: te recomiendo ver la issue #78
