### ISSUE TITLE
Entrega 2 Par Apartado 2.4.7

### ISSUE THREAD

**Issue by MotxiGer** [IIC2413/Syllabus-2021-2#84]
Respecto a esta pregunta, si un usuario que ya está suscrito cancela su suscripción y luego de un tiempo se vuelve a suscribir el id de la primera suscripción se queda (se actualiza la fila) ó se crea una nueva fila con un nuevo ID

**Comment by arpincheira** [comment]
Que el usuario canceló la subscripción. No, no existe ningún tipo de reembolso, pero lo que implica en su mayoría es que no seguirá pagando el servicio. Recomiendo ahondar un poco más en esto a partir de la visualización del registro de pagos.
