### ISSUE TITLE
Entrega 2 consulta 5

### ISSUE THREAD

**Issue by matildeotte** [IIC2413/Syllabus-2021-2#85]
Hola! 

Quería saber si en la consulta 5 debo mostrar sólo los juegos de pago único (ya que esos son lo únicos asociados a un proveedor) o debo incluirlos todos y en los que sean de suscripción simplemente se deja la casilla de proveedor vacía. 

Gracias!

**Comment by arpincheira** [comment]
Hola, los juegos por subscripción si están relacionados con los proveedores (spoiler), ahora, recomiendo que revises los datos entregados para averiguar cuales son

**Comment by arpincheira** [comment]
Hola nuevamente, estaba reconsiderando la pregunta y aquí hay un supuesto que pueden realizar para realizar dicha asociación: Un videojuego de subscripción pertenece a un usuario a través del primer proveedor que tenga dicho juego y que provea juegos al usuario( **pista:**  Recomiendo fuertemente considerar el orden de aparición de la relación entre usuario y proveedor en el archivo `usuario_proveedor.csv`). Espero que eso les sea de ayuda

**Comment by arpincheira** [comment]
Hola, lamento la demora, la idea es esta: supongamos que existe un usuario 1 que está suscrito a un juego x el cual está conectado al proveedor 2 y al 3. Ahora, si el usuario posee el siguiente dato en usuario proveedor:

id_usuario        | id_proveedor   |
---------------- |--------- |
1       | 1    | 
1       | 2    |
1       | 3   | 

La idea del supuesto es tomar el primero de estos que coincida con la condición de que provee juegos al usuario y posee dicho juego, es decir, el proveedor que da el juego por subscripción x al usuario 1 es el poroveedor de id 2
