### ISSUE TITLE
Consulta 1 : pregunta de enunciado

### ISSUE THREAD

**Issue by rfigueroa314** [IIC2413/Syllabus-2021-2#94]
En la consulta 1 la respuesta debe ser la cantidad de ko, asistencias y sumas de puntajes **por cada partida**. O debe ser la cantidad de ko, asistencias y sumas de puntajes **entre todas las partidas**.

**Comment by ironcadiz** [comment]
Entre todas las partidas. No es necesario hacer un desglose por partida.
