### ISSUE TITLE
Duda respecto a las funciones hash

### ISSUE THREAD

**Issue by Nicolasramos411** [IIC2413/Syllabus-2021-2#98]
Hola!

En clases hablamos de las funciones hash, de los beneficios que tiene el usar este tipo de funciones como su bajo costo computacional y sobre el recorrido de la función, en especial cuando ocurren colisiones. Mi duda es la siguiente:

- Dada una función hash H tal que H: D -> R, con D un conjunto dominio finito y R un conjunto recorrido finito también. Como los conjuntos mencionados pueden no ser del mismo tamaño, ¿En qué influiría si la función es inyectiva ó sobreyectiva? y, en el caso de que los conjuntos si sean del mismo tamaño, ¿En que influiría si la función es biyectiva?, ¿Tiene alguna ventaja o desventaja el hecho que la función tenga inversa?,

Muchas gracias!

**Comment by rjherrera** [comment]
En general las funciones de hash no intentan ser inyectivas porque mapean un dominio arbitrariamente grande a uno acotado. Hay algunos usos en los que se intenta usar funciones inyectivas, pero no es la generalidad. De hecho por ejemplo funciones como SHA256 reciben input de tamaño fijo de 512 bits agregándole padding a los inputs que no lleguen a ese porte, y el output es de 256 bits, por lo tanto no puede ser inyectiva.

En términos de ventajas y desventajas las funciones perfectas de hash (que son inyectivas) tienen algunas ventajas en términos de tiempo, pero funcionan como tablas de permutaciones, entonces tienen un alto uso de espacio (se tiene que saber el tamaño del dominio de antemano y la función es de tamaño proporcional a eso). Eso sí, las funciones perfectas de hash perfectas no son necesariamente biyectivas.

Las funciones de hash en general tienen varios usos, siendo bien típicos los usos en criptografía, ahí un requerimiento es que sean funciones one-way, o sea que no se pueden invertir. Para ciertas aplicaciones de bases de datos podría una función de hash perfecta ser útil, pero en realidad lo que termina pasando es que uno se abstrae de la función en particular y se queda más con las características generales de los hash index, porque el dbms decide qué función usa generalmente.
